"""Seed additional colectivos culturales into the database."""
from app.database import supabase

colectivos = [
    # ── HIP-HOP / FREESTYLE ──────────────────────────────
    {
        "nombre": "4 Elementos Skuela",
        "slug": "4-elementos-skuela",
        "tipo": "colectivo",
        "categoria_principal": "hip_hop",
        "categorias": ["hip_hop", "batalla_freestyle", "danza"],
        "descripcion": "Escuela de cultura hip-hop integral: MC, DJ, breaking y graffiti. Formación para jóvenes de comunas populares de Medellín.",
        "descripcion_corta": "Escuela de cultura hip-hop integral en Medellín",
        "municipio": "medellin",
        "barrio": "Aranjuez",
        "instagram_handle": "4elementosskuela",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Revolución Sin Muertos",
        "slug": "revolucion-sin-muertos",
        "tipo": "colectivo",
        "categoria_principal": "hip_hop",
        "categorias": ["hip_hop", "poesia", "festival"],
        "descripcion": "Colectivo hip-hop comprometido con la transformación social a través del rap consciente, spoken word y festivales barriales.",
        "descripcion_corta": "Hip-hop consciente y transformación social",
        "municipio": "medellin",
        "barrio": "San Javier",
        "instagram_handle": "revolucionsinmuertos",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Crew Peligrosos",
        "slug": "crew-peligrosos-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "hip_hop",
        "categorias": ["hip_hop", "batalla_freestyle", "festival"],
        "descripcion": "Referentes del hip-hop en la Comuna 13. Organizan el Revolución Sin Muertos Festival y promueven la cultura urbana como herramienta de paz.",
        "descripcion_corta": "Referentes del hip-hop en la Comuna 13",
        "municipio": "medellin",
        "barrio": "San Javier",
        "instagram_handle": "crewpeligrosos",
        "sitio_web": "https://www.crewpeligrosos.com",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Kinética Crew",
        "slug": "kinetica-crew",
        "tipo": "colectivo",
        "categoria_principal": "hip_hop",
        "categorias": ["hip_hop", "danza", "batalla_freestyle"],
        "descripcion": "Crew de breaking y danza urbana. Batallas, showcases y talleres de b-boying en Medellín.",
        "descripcion_corta": "Breaking y danza urbana en Medellín",
        "municipio": "medellin",
        "barrio": "Castilla",
        "instagram_handle": "kineticacrew",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "La Élite del Rap",
        "slug": "la-elite-del-rap",
        "tipo": "colectivo",
        "categoria_principal": "batalla_freestyle",
        "categorias": ["batalla_freestyle", "hip_hop"],
        "descripcion": "Organizadores de batallas de freestyle en Medellín. Competencias semanales abiertas para MCs de todos los niveles.",
        "descripcion_corta": "Batallas de freestyle semanales en Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "laelitedelrap",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "AKA Freestyle",
        "slug": "aka-freestyle-medellin",
        "tipo": "colectivo",
        "categoria_principal": "batalla_freestyle",
        "categorias": ["batalla_freestyle", "hip_hop"],
        "descripcion": "Plataforma de batallas de rap y freestyle en el Valle de Aburrá. Eventos en plazas y parques públicos.",
        "descripcion_corta": "Batallas de freestyle en plazas del Valle de Aburrá",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "akafreestyle",
        "nivel_actividad": "activo",
    },
    # ── ELECTRÓNICA / MÚSICA ──────────────────────────────
    {
        "nombre": "Sónicos Colectivo",
        "slug": "sonicos-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "electronica",
        "categorias": ["electronica", "musica_en_vivo"],
        "descripcion": "Colectivo de música electrónica experimental. Raves underground, sesiones de ambient y talleres de producción.",
        "descripcion_corta": "Electrónica experimental y raves underground",
        "municipio": "medellin",
        "barrio": "Prado",
        "instagram_handle": "sonicoscolectivo",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Boiler Underground MDE",
        "slug": "boiler-underground-mde",
        "tipo": "colectivo",
        "categoria_principal": "electronica",
        "categorias": ["electronica", "musica_en_vivo"],
        "descripcion": "Sesiones de DJ sets y electrónica en espacios no convencionales de Medellín. Techno, house y bass music.",
        "descripcion_corta": "DJ sets y electrónica en espacios no convencionales",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "boilerundergroundmde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Selva Electrónica",
        "slug": "selva-electronica",
        "tipo": "colectivo",
        "categoria_principal": "electronica",
        "categorias": ["electronica", "festival"],
        "descripcion": "Festival y colectivo de electrónica al aire libre. Fusión de sonidos tropicales con bass music y techno en entornos naturales.",
        "descripcion_corta": "Electrónica al aire libre con sonidos tropicales",
        "municipio": "medellin",
        "barrio": "Santa Elena",
        "instagram_handle": "selvaelectronica",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Resonancia Medellín",
        "slug": "resonancia-medellin",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "jazz", "electronica"],
        "descripcion": "Plataforma para músicos emergentes. Jam sessions, showcases y residencias artísticas en bares y galerías de Medellín.",
        "descripcion_corta": "Plataforma para músicos emergentes de Medellín",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "resonanciamde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Jazz al Parque Medellín",
        "slug": "jazz-al-parque-medellin",
        "tipo": "colectivo",
        "categoria_principal": "jazz",
        "categorias": ["jazz", "musica_en_vivo"],
        "descripcion": "Colectivo que promueve el jazz en espacios públicos de Medellín. Conciertos gratuitos en parques, jam sessions y talleres.",
        "descripcion_corta": "Jazz gratuito en parques de Medellín",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "jazzalparkemde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Cumbia Underground",
        "slug": "cumbia-underground",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival"],
        "descripcion": "Rescate de la cumbia y músicas del Caribe colombiano con fusiones electrónicas. Fiestas temáticas y talleres de percusión.",
        "descripcion_corta": "Cumbia y fusiones electrónicas del Caribe",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "cumbiaunderground",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Sexteto Medellin",
        "slug": "sexteto-medellin",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival"],
        "descripcion": "Agrupación de música afro-colombiana y salsa. Toques en bares, festivales y eventos culturales del Valle de Aburrá.",
        "descripcion_corta": "Música afro-colombiana y salsa en vivo",
        "municipio": "medellin",
        "barrio": "Manrique",
        "instagram_handle": "sextetomedellin",
        "nivel_actividad": "activo",
    },
    # ── TEATRO / DANZA / CIRCO ────────────────────────────
    {
        "nombre": "Colectivo Escénico Entrénate",
        "slug": "colectivo-escenico-entrenate",
        "tipo": "colectivo",
        "categoria_principal": "teatro",
        "categorias": ["teatro", "danza"],
        "descripcion": "Teatro experimental y laboratorio de creación escénica. Obras site-specific, performance y talleres de dramaturgia.",
        "descripcion_corta": "Teatro experimental y laboratorio escénico",
        "municipio": "medellin",
        "barrio": "Buenos Aires",
        "instagram_handle": "colectivoentrenate",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Teatro La Mosca",
        "slug": "teatro-la-mosca",
        "tipo": "colectivo",
        "categoria_principal": "teatro",
        "categorias": ["teatro", "circo"],
        "descripcion": "Compañía de teatro callejero y circo contemporáneo. Intervenciones urbanas, zancos y acrobacia aérea en plazas públicas.",
        "descripcion_corta": "Teatro callejero y circo contemporáneo",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "teatrolamosca",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Cuerpo Gráfico Danza",
        "slug": "cuerpo-grafico-danza",
        "tipo": "colectivo",
        "categoria_principal": "danza",
        "categorias": ["danza", "arte_contemporaneo"],
        "descripcion": "Compañía de danza contemporánea. Exploración del movimiento, coreografía experimental y piezas interdisciplinarias.",
        "descripcion_corta": "Danza contemporánea y coreografía experimental",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "cuerpografico",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Danza Libre Antioquia",
        "slug": "danza-libre-antioquia",
        "tipo": "colectivo",
        "categoria_principal": "danza",
        "categorias": ["danza", "festival"],
        "descripcion": "Red de bailarines y coreógrafos de Antioquia. Festivales de danza, talleres abiertos y encuentros de movimiento libre.",
        "descripcion_corta": "Red de danza contemporánea de Antioquia",
        "municipio": "medellin",
        "barrio": "Belén",
        "instagram_handle": "danzalibreantioquia",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Circo Medellín",
        "slug": "circo-medellin",
        "tipo": "colectivo",
        "categoria_principal": "circo",
        "categorias": ["circo", "teatro", "festival"],
        "descripcion": "Escuela y compañía de circo contemporáneo. Acrobacia, malabares, telas aéreas y clown. Espectáculos en parques y teatros.",
        "descripcion_corta": "Circo contemporáneo: acrobacia, malabares y clown",
        "municipio": "medellin",
        "barrio": "Robledo",
        "instagram_handle": "circomedellin",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Mimo Urbano Colectivo",
        "slug": "mimo-urbano-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "teatro",
        "categorias": ["teatro", "circo"],
        "descripcion": "Arte del mimo y la pantomima en las calles de Medellín. Intervenciones urbanas, talleres de expresión corporal y espectáculos silentes.",
        "descripcion_corta": "Mimo y pantomima en las calles de Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "mimourbanomde",
        "nivel_actividad": "moderado",
    },
    # ── GALERÍA / ARTE CONTEMPORÁNEO ──────────────────────
    {
        "nombre": "Taller 7",
        "slug": "taller-7-medellin",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "arte_contemporaneo"],
        "descripcion": "Espacio autogestionado de artistas visuales. Exposiciones, talleres de grabado, serigrafía y arte impreso.",
        "descripcion_corta": "Espacio autogestionado de arte visual e impreso",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "taller7mde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "La Mutante",
        "slug": "la-mutante-medellin",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "arte_contemporaneo", "editorial"],
        "descripcion": "Galería independiente y editorial de arte contemporáneo. Exposiciones, publicaciones y residencias artísticas.",
        "descripcion_corta": "Galería independiente y editorial de arte",
        "municipio": "medellin",
        "barrio": "Carlos E. Restrepo",
        "instagram_handle": "lamutantemde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Platohedro",
        "slug": "platohedro-medellin",
        "tipo": "colectivo",
        "categoria_principal": "arte_contemporaneo",
        "categorias": ["arte_contemporaneo", "editorial", "galeria"],
        "descripcion": "Laboratorio de creación comunitaria en el barrio Buenos Aires. Arte, tecnología, editorial y cultura libre.",
        "descripcion_corta": "Laboratorio de creación comunitaria: arte, tecnología y cultura libre",
        "municipio": "medellin",
        "barrio": "Buenos Aires",
        "instagram_handle": "platohedro",
        "sitio_web": "https://platohedro.org",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Arte en Ruinas",
        "slug": "arte-en-ruinas",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "arte_contemporaneo", "fotografia"],
        "descripcion": "Intervenciones artísticas en edificios abandonados y espacios en desuso de Medellín. Arte efímero, instalaciones y fotografía urbana.",
        "descripcion_corta": "Arte en espacios abandonados de Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "arteenruinas",
        "nivel_actividad": "moderado",
    },
    # ── MURALISMO / GRAFFITI ──────────────────────────────
    {
        "nombre": "Ciudad Gráfica",
        "slug": "ciudad-grafica",
        "tipo": "colectivo",
        "categoria_principal": "muralismo",
        "categorias": ["muralismo", "galeria"],
        "descripcion": "Colectivo de muralistas y grafiteros. Intervenciones en fachadas, murales comunitarios y festivales de arte urbano.",
        "descripcion_corta": "Muralismo y arte urbano en fachadas de Medellín",
        "municipio": "medellin",
        "barrio": "San Javier",
        "instagram_handle": "ciudadgrafica",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Graficalia",
        "slug": "graficalia-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "muralismo",
        "categorias": ["muralismo", "festival", "galeria"],
        "descripcion": "Festival internacional de muralismo y graffiti en Medellín. Convoca artistas urbanos de todo el mundo para pintar la ciudad.",
        "descripcion_corta": "Festival internacional de muralismo y graffiti",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "graficalia",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Aerosol Queens",
        "slug": "aerosol-queens",
        "tipo": "colectivo",
        "categoria_principal": "muralismo",
        "categorias": ["muralismo", "galeria"],
        "descripcion": "Colectivo femenino de graffiti y muralismo. Visibilización del arte urbano hecho por mujeres en Medellín.",
        "descripcion_corta": "Graffiti y muralismo femenino en Medellín",
        "municipio": "medellin",
        "barrio": "Envigado",
        "instagram_handle": "aerosolqueens",
        "nivel_actividad": "activo",
    },
    # ── POESÍA / LITERATURA / EDITORIAL ───────────────────
    {
        "nombre": "Poesía en Voz Alta",
        "slug": "poesia-en-voz-alta-mde",
        "tipo": "colectivo",
        "categoria_principal": "poesia",
        "categorias": ["poesia", "editorial"],
        "descripcion": "Colectivo de poesía oral y spoken word. Recitales abiertos, slams de poesía y talleres de escritura creativa en bares y parques.",
        "descripcion_corta": "Poesía oral, slams y spoken word en Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "poesiaenvozalta",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Letra Salvaje",
        "slug": "letra-salvaje",
        "tipo": "colectivo",
        "categoria_principal": "poesia",
        "categorias": ["poesia", "editorial", "libreria"],
        "descripcion": "Editorial independiente y colectivo literario. Publicaciones de poesía, fanzines y talleres de creación literaria.",
        "descripcion_corta": "Editorial independiente y fanzines literarios",
        "municipio": "medellin",
        "barrio": "Prado",
        "instagram_handle": "letrasalvaje",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Tragaluz Editores",
        "slug": "tragaluz-editores-mde",
        "tipo": "colectivo",
        "categoria_principal": "editorial",
        "categorias": ["editorial", "libreria"],
        "descripcion": "Editorial independiente de Medellín especializada en libros ilustrados, poesía visual y literatura infantil/juvenil.",
        "descripcion_corta": "Editorial independiente de libros ilustrados",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "tragaluzeditores",
        "sitio_web": "https://www.tragaluzeditores.com",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Fanzinópolis",
        "slug": "fanzinopolis",
        "tipo": "colectivo",
        "categoria_principal": "editorial",
        "categorias": ["editorial", "galeria", "fotografia"],
        "descripcion": "Colectivo de autoedición y fanzines. Ferias de publicaciones independientes, talleres de risografía y encuadernación.",
        "descripcion_corta": "Fanzines, autoedición y publicaciones independientes",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "fanzinopolis",
        "nivel_actividad": "activo",
    },
    # ── FOTOGRAFÍA ────────────────────────────────────────
    {
        "nombre": "Ojo de Pez Fotografía",
        "slug": "ojo-de-pez-fotografia",
        "tipo": "colectivo",
        "categoria_principal": "fotografia",
        "categorias": ["fotografia", "galeria"],
        "descripcion": "Colectivo de fotografía documental y artística. Exposiciones, photo walks y talleres de fotografía callejera en Medellín.",
        "descripcion_corta": "Fotografía documental y artística en Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "ojodepezfoto",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Colectivo Visible",
        "slug": "colectivo-visible",
        "tipo": "colectivo",
        "categoria_principal": "fotografia",
        "categorias": ["fotografia", "galeria", "editorial"],
        "descripcion": "Fotografía social y memoria visual del Valle de Aburrá. Proyectos documentales, exposiciones y archivo fotográfico comunitario.",
        "descripcion_corta": "Fotografía social y memoria visual del Valle de Aburrá",
        "municipio": "medellin",
        "barrio": "Buenos Aires",
        "instagram_handle": "colectivovisible",
        "nivel_actividad": "moderado",
    },
    # ── CINE ──────────────────────────────────────────────
    {
        "nombre": "Cine al Parche",
        "slug": "cine-al-parche",
        "tipo": "colectivo",
        "categoria_principal": "cine",
        "categorias": ["cine", "festival"],
        "descripcion": "Proyecciones de cine independiente y documental en espacios públicos. Cine foros, cortometrajes y documentales sociales.",
        "descripcion_corta": "Cine independiente y documental al aire libre",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "cinealparche",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Medellín Audiovisual",
        "slug": "medellin-audiovisual",
        "tipo": "colectivo",
        "categoria_principal": "cine",
        "categorias": ["cine", "fotografia"],
        "descripcion": "Red de cineastas y realizadores audiovisuales de Medellín. Talleres de producción, rodajes colectivos y proyecciones.",
        "descripcion_corta": "Red de cineastas y realizadores audiovisuales",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "mdeaudiovisual",
        "nivel_actividad": "activo",
    },
    # ── FILOSOFÍA (más) ───────────────────────────────────
    {
        "nombre": "Sócrates en la Calle",
        "slug": "socrates-en-la-calle",
        "tipo": "colectivo",
        "categoria_principal": "filosofia",
        "categorias": ["filosofia", "poesia"],
        "descripcion": "Diálogos socráticos en plazas públicas de Medellín. Preguntas abiertas, debates filosóficos y tertulias ciudadanas sobre la vida cotidiana.",
        "descripcion_corta": "Diálogos socráticos en plazas públicas de Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "socratesenlanoche",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Rizoma Colectivo Filosófico",
        "slug": "rizoma-colectivo-filosofico",
        "tipo": "colectivo",
        "categoria_principal": "filosofia",
        "categorias": ["filosofia", "editorial"],
        "descripcion": "Pensamiento rizomático: filosofía post-estructuralista, estudios decoloniales y ecología política. Seminarios y publicaciones.",
        "descripcion_corta": "Filosofía post-estructuralista y estudios decoloniales",
        "municipio": "envigado",
        "barrio": "Centro",
        "instagram_handle": "rizomamde",
        "nivel_actividad": "moderado",
    },
    # ── VALLE DE ABURRÁ (otros municipios) ────────────────
    {
        "nombre": "Envigado Suena",
        "slug": "envigado-suena",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival"],
        "descripcion": "Plataforma de música independiente de Envigado. Conciertos en parques, festivales locales y apoyo a bandas emergentes.",
        "descripcion_corta": "Música independiente y festivales en Envigado",
        "municipio": "envigado",
        "barrio": "Centro",
        "instagram_handle": "envigadosuena",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Bello Cultural",
        "slug": "bello-cultural-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "teatro", "musica_en_vivo"],
        "descripcion": "Red cultural del municipio de Bello. Articulación de artistas, gestores y espacios culturales del norte del Valle de Aburrá.",
        "descripcion_corta": "Red cultural y artística de Bello",
        "municipio": "bello",
        "barrio": "Centro",
        "instagram_handle": "bellocultural",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Itagüí Crea",
        "slug": "itagui-crea",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "galeria", "musica_en_vivo"],
        "descripcion": "Colectivo de creación artística de Itagüí. Talleres comunitarios, exposiciones y festivales culturales.",
        "descripcion_corta": "Creación artística comunitaria en Itagüí",
        "municipio": "itagui",
        "barrio": "Centro",
        "instagram_handle": "itaguicrea",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Sabaneta Artística",
        "slug": "sabaneta-artistica",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "musica_en_vivo", "festival"],
        "descripcion": "Agenda artística y cultural de Sabaneta. Exposiciones al aire libre, toques acústicos y mercados creativos.",
        "descripcion_corta": "Agenda artística y mercados creativos en Sabaneta",
        "municipio": "sabaneta",
        "barrio": "Centro",
        "instagram_handle": "sabanetaartistica",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "La Estrella Creativa",
        "slug": "la-estrella-creativa",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "teatro", "danza"],
        "descripcion": "Colectivo de artes escénicas del municipio de La Estrella. Teatro comunitario, danza y formación artística.",
        "descripcion_corta": "Artes escénicas comunitarias en La Estrella",
        "municipio": "la_estrella",
        "barrio": "Centro",
        "instagram_handle": "laestrellacreativa",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Copacabana en Escena",
        "slug": "copacabana-en-escena",
        "tipo": "colectivo",
        "categoria_principal": "teatro",
        "categorias": ["teatro", "danza", "musica_en_vivo"],
        "descripcion": "Colectivo de artes escénicas de Copacabana. Funciones de teatro al aire libre, danza folclórica y conciertos comunitarios.",
        "descripcion_corta": "Artes escénicas y teatro comunitario en Copacabana",
        "municipio": "copacabana",
        "barrio": "Centro",
        "instagram_handle": "copacabanaenescena",
        "nivel_actividad": "moderado",
    },
    # ── UNDERGROUND / MIXTOS ──────────────────────────────
    {
        "nombre": "La Pascasia",
        "slug": "la-pascasia-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "musica_en_vivo", "editorial"],
        "descripcion": "Espacio autogestionado de arte y música en el barrio Prado. Exposiciones, conciertos íntimos, lanzamientos de fanzines y noches de poesía.",
        "descripcion_corta": "Arte, música y fanzines en el barrio Prado",
        "municipio": "medellin",
        "barrio": "Prado",
        "instagram_handle": "lapascasia",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Colectivo Contravía",
        "slug": "colectivo-contravia",
        "tipo": "colectivo",
        "categoria_principal": "arte_contemporaneo",
        "categorias": ["arte_contemporaneo", "galeria", "editorial"],
        "descripcion": "Colectivo interdisciplinario de arte contemporáneo. Intervenciones urbanas, performance, videoarte y publicaciones críticas.",
        "descripcion_corta": "Arte contemporáneo interdisciplinario y performance",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "colectivocontravia",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Frecuencia Libre",
        "slug": "frecuencia-libre",
        "tipo": "colectivo",
        "categoria_principal": "radio_comunitaria",
        "categorias": ["radio_comunitaria", "musica_en_vivo", "poesia"],
        "descripcion": "Radio comunitaria online y podcast cultural. Difusión de música independiente, entrevistas a artistas locales y programas de poesía.",
        "descripcion_corta": "Radio comunitaria y podcast cultural de Medellín",
        "municipio": "medellin",
        "barrio": "Aranjuez",
        "instagram_handle": "frecuencialibre",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Tránsito Colectivo",
        "slug": "transito-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "danza",
        "categorias": ["danza", "teatro", "circo"],
        "descripcion": "Colectivo de artes del movimiento. Fusión de danza contemporánea, contact improvisation y artes circenses.",
        "descripcion_corta": "Artes del movimiento y contact improvisation",
        "municipio": "medellin",
        "barrio": "Suramericana",
        "instagram_handle": "transitocolectivo",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Nodo Cultural Medellín",
        "slug": "nodo-cultural-medellin",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "galeria", "musica_en_vivo", "teatro"],
        "descripcion": "Red de gestores culturales que conecta espacios, artistas y comunidades. Eventos colaborativos, mapeo cultural y formación.",
        "descripcion_corta": "Red de gestores culturales del Valle de Aburrá",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "nodoculturalmde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Mantis Colectivo",
        "slug": "mantis-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "electronica",
        "categorias": ["electronica", "arte_contemporaneo"],
        "descripcion": "Arte sonoro y música experimental. Instalaciones sonoras, performances audiovisuales y laboratorio de síntesis modular.",
        "descripcion_corta": "Arte sonoro y música experimental",
        "municipio": "medellin",
        "barrio": "Carlos E. Restrepo",
        "instagram_handle": "mantiscolectivo",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Raíces Urbanas",
        "slug": "raices-urbanas-mde",
        "tipo": "colectivo",
        "categoria_principal": "hip_hop",
        "categorias": ["hip_hop", "danza", "muralismo"],
        "descripcion": "Cultura urbana para la transformación social en comunas populares. Hip-hop, breaking, graffiti y talleres para jóvenes.",
        "descripcion_corta": "Cultura urbana y transformación social en comunas",
        "municipio": "medellin",
        "barrio": "Popular",
        "instagram_handle": "raicesurbanasmde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Semilla Sonora",
        "slug": "semilla-sonora",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival", "casa_cultura"],
        "descripcion": "Formación musical para niños y jóvenes de barrios populares. Ensambles, coros y presentaciones en espacios comunitarios.",
        "descripcion_corta": "Formación musical para niños y jóvenes de barrios populares",
        "municipio": "medellin",
        "barrio": "Santo Domingo",
        "instagram_handle": "semillasonora",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Colectivo Nómada Visual",
        "slug": "colectivo-nomada-visual",
        "tipo": "colectivo",
        "categoria_principal": "fotografia",
        "categorias": ["fotografia", "cine", "editorial"],
        "descripcion": "Producción audiovisual independiente: documentales, cortometrajes y proyectos de fotografía social en el Valle de Aburrá.",
        "descripcion_corta": "Producción audiovisual independiente y documentales",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "nomadavisual",
        "nivel_actividad": "activo",
    },
]

inserted = 0
skipped = 0
for col in colectivos:
    existing = supabase.table("lugares").select("id").eq("slug", col["slug"]).execute()
    if existing.data:
        print(f"  Skip: {col['nombre']}")
        skipped += 1
        continue
    supabase.table("lugares").insert(col).execute()
    print(f"  OK: {col['nombre']}")
    inserted += 1

print(f"\nDone! Inserted: {inserted}, Skipped: {skipped}")
