"""Seed colectivos v2 — más categorías, más municipios, más diversidad."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from app.database import supabase

colectivos = [
    # ── JAZZ ─────────────────────────────────────────────────────────────
    {
        "nombre": "Jam Session Laureles",
        "slug": "jam-session-laureles",
        "tipo": "colectivo",
        "categoria_principal": "jazz",
        "categorias": ["jazz", "musica_en_vivo"],
        "descripcion": "Jam sessions semanales de jazz en bares y cafés del corredor de Laureles. Músicos de todos los niveles bienvenidos.",
        "descripcion_corta": "Jam sessions de jazz en Laureles",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "jamsessionlaureles",
        "nivel_actividad": "muy_activo",
        "es_underground": True,
    },
    {
        "nombre": "Estándar de Jazz Medellín",
        "slug": "estandar-jazz-medellin",
        "tipo": "colectivo",
        "categoria_principal": "jazz",
        "categorias": ["jazz", "musica_en_vivo", "festival"],
        "descripcion": "Colectivo dedicado a los estándares del jazz: bebop, hard bop y jazz contemporáneo. Ciclos de conciertos en el Centro y El Poblado.",
        "descripcion_corta": "Jazz estándar: bebop, hard bop y jazz contemporáneo",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "estandarjazzmde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Jazz & Vinos Medellín",
        "slug": "jazz-vinos-medellin",
        "tipo": "colectivo",
        "categoria_principal": "jazz",
        "categorias": ["jazz", "musica_en_vivo"],
        "descripcion": "Noches de jazz y maridaje en restaurantes y vinotecas de Medellín. Conciertos íntimos en formato acústico.",
        "descripcion_corta": "Noches de jazz en restaurantes y vinotecas",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "jazzyvinosmde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Free Jazz Colectivo MDE",
        "slug": "free-jazz-colectivo-mde",
        "tipo": "colectivo",
        "categoria_principal": "jazz",
        "categorias": ["jazz", "electronica", "arte_contemporaneo"],
        "descripcion": "Exploración del free jazz, la improvisación libre y la fusión con electrónica. Conciertos en galerías y espacios alternativos.",
        "descripcion_corta": "Free jazz e improvisación libre",
        "municipio": "medellin",
        "barrio": "Carlos E. Restrepo",
        "instagram_handle": "freejazzmde",
        "nivel_actividad": "moderado",
        "es_underground": True,
    },
    {
        "nombre": "Trío de Cuerdas Jazz Sur",
        "slug": "trio-cuerdas-jazz-sur",
        "tipo": "colectivo",
        "categoria_principal": "jazz",
        "categorias": ["jazz", "musica_en_vivo"],
        "descripcion": "Agrupación de jazz de cámara del sur del Valle de Aburrá. Conciertos en Sabaneta, Envigado e Itagüí.",
        "descripcion_corta": "Jazz de cámara en el sur del Valle de Aburrá",
        "municipio": "envigado",
        "barrio": "Las Vegas",
        "instagram_handle": "triocuerdasjazzsur",
        "nivel_actividad": "activo",
    },

    # ── EDITORIAL / LIBRERÍA ────────────────────────────────────────────
    {
        "nombre": "Sílaba Editores",
        "slug": "silaba-editores-mde",
        "tipo": "colectivo",
        "categoria_principal": "editorial",
        "categorias": ["editorial", "libreria"],
        "descripcion": "Editorial universitaria de Medellín con sello en humanidades, ciencias sociales y literatura. Ferias del libro y charlas con autores.",
        "descripcion_corta": "Editorial académica y literaria de Medellín",
        "municipio": "medellin",
        "barrio": "Buenos Aires",
        "instagram_handle": "silabaeditoresmde",
        "sitio_web": "https://www.silabaeditoresmde.com",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "La Carreta Editores",
        "slug": "la-carreta-editores",
        "tipo": "colectivo",
        "categoria_principal": "editorial",
        "categorias": ["editorial", "libreria"],
        "descripcion": "Sello editorial antioqueño especializado en historia, memoria y cultura local. Publicaciones sobre el Valle de Aburrá y sus comunidades.",
        "descripcion_corta": "Editorial sobre historia y cultura antioqueña",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "lacarretaeditores",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Libros & Letras Laureles",
        "slug": "libros-letras-laureles",
        "tipo": "colectivo",
        "categoria_principal": "libreria",
        "categorias": ["libreria", "editorial", "poesia"],
        "descripcion": "Librería independiente con club de lectura semanal, talleres de escritura y presentaciones de libros de autores locales.",
        "descripcion_corta": "Librería independiente con club de lectura en Laureles",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "librosyltraslaureles",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "El Ático Libros",
        "slug": "el-atico-libros",
        "tipo": "colectivo",
        "categoria_principal": "libreria",
        "categorias": ["libreria", "editorial", "poesia"],
        "descripcion": "Librería de viejo y nueva con café. Colección de autores latinoamericanos, fanzines y publicaciones de autoedición.",
        "descripcion_corta": "Librería de viejo con café y fanzines",
        "municipio": "medellin",
        "barrio": "Prado",
        "instagram_handle": "elaticolibros",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Feria del Libro Independiente Aburrá",
        "slug": "feria-libro-independiente-aburra",
        "tipo": "colectivo",
        "categoria_principal": "editorial",
        "categorias": ["editorial", "libreria", "festival"],
        "descripcion": "Organización de la feria de publicaciones independientes del Valle de Aburrá. Editoriales pequeñas, fanzines, zines y autoedición.",
        "descripcion_corta": "Feria de publicaciones independientes del Valle de Aburrá",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "ferialibromde",
        "nivel_actividad": "activo",
    },

    # ── RADIO COMUNITARIA / PODCAST ─────────────────────────────────────
    {
        "nombre": "Radio Pacífica MDE",
        "slug": "radio-pacifica-mde",
        "tipo": "colectivo",
        "categoria_principal": "radio_comunitaria",
        "categorias": ["radio_comunitaria", "musica_en_vivo"],
        "descripcion": "Emisora comunitaria del barrio Manrique. Programación de músicas del Pacífico, vallenato, hip-hop y noticias barriales.",
        "descripcion_corta": "Radio comunitaria con músicas del Pacífico en Manrique",
        "municipio": "medellin",
        "barrio": "Manrique",
        "instagram_handle": "radiopacificamde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Antena Libre MDE",
        "slug": "antena-libre-mde",
        "tipo": "colectivo",
        "categoria_principal": "radio_comunitaria",
        "categorias": ["radio_comunitaria", "poesia", "musica_en_vivo"],
        "descripcion": "Plataforma de podcast y streaming cultural. Arte, política, ecología y música independiente desde Medellín.",
        "descripcion_corta": "Podcast cultural: arte, política y música independiente",
        "municipio": "medellin",
        "barrio": "Aranjuez",
        "instagram_handle": "antenalibremde",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "La Voz del Barrio Popular",
        "slug": "la-voz-del-barrio-popular",
        "tipo": "colectivo",
        "categoria_principal": "radio_comunitaria",
        "categorias": ["radio_comunitaria", "hip_hop"],
        "descripcion": "Radio comunitaria del nororiente de Medellín. Hip-hop, noticias comunitarias y espacios de participación juvenil.",
        "descripcion_corta": "Radio comunitaria del nororiente: hip-hop y participación juvenil",
        "municipio": "medellin",
        "barrio": "Popular",
        "instagram_handle": "lavozdelbarriopop",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Ondas Belén FM",
        "slug": "ondas-belen-fm",
        "tipo": "colectivo",
        "categoria_principal": "radio_comunitaria",
        "categorias": ["radio_comunitaria", "musica_en_vivo", "casa_cultura"],
        "descripcion": "Emisora comunitaria de Belén. Programación variada: música en vivo, entrevistas a artistas locales y agenda cultural.",
        "descripcion_corta": "Radio comunitaria de Belén con música en vivo",
        "municipio": "medellin",
        "barrio": "Belén",
        "instagram_handle": "ondasbelenfm",
        "nivel_actividad": "moderado",
    },

    # ── POESÍA / SLAM ───────────────────────────────────────────────────
    {
        "nombre": "Slam Medellín",
        "slug": "slam-medellin",
        "tipo": "colectivo",
        "categoria_principal": "poesia",
        "categorias": ["poesia", "teatro"],
        "descripcion": "Competencias de slam poetry en Medellín. Poetas suben al escenario y el público decide. Formato accesible, diverso e irreverente.",
        "descripcion_corta": "Slam poetry competitivo y accesible en Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "slamedellin",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Spoken Word Antioquia",
        "slug": "spoken-word-antioquia",
        "tipo": "colectivo",
        "categoria_principal": "poesia",
        "categorias": ["poesia", "teatro", "musica_en_vivo"],
        "descripcion": "Performances de spoken word con música en vivo. Fusión de poesía oral, jazz y electrónica en escenarios del Valle de Aburrá.",
        "descripcion_corta": "Spoken word con música en vivo",
        "municipio": "medellin",
        "barrio": "Carlos E. Restrepo",
        "instagram_handle": "spokenwdantioquia",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Versos Urbanos",
        "slug": "versos-urbanos-mde",
        "tipo": "colectivo",
        "categoria_principal": "poesia",
        "categorias": ["poesia", "hip_hop", "muralismo"],
        "descripcion": "Poesía en las calles: muros escritos, declamaciones en parques y batalla de versos. Poesía comprometida con el territorio.",
        "descripcion_corta": "Poesía callejera y muros escritos en Medellín",
        "municipio": "medellin",
        "barrio": "Manrique",
        "instagram_handle": "versosurbanosco",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "El Paréntesis Poético",
        "slug": "el-parentesis-poetico",
        "tipo": "colectivo",
        "categoria_principal": "poesia",
        "categorias": ["poesia", "editorial"],
        "descripcion": "Tertulias de poesía en librerías y cafés de El Poblado y Laureles. Lectura en voz alta, crítica literaria y publicación de plaquettes.",
        "descripcion_corta": "Tertulias de poesía y publicación de plaquettes",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "elparentesispoet",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Poetas del Aburrá",
        "slug": "poetas-del-aburra",
        "tipo": "colectivo",
        "categoria_principal": "poesia",
        "categorias": ["poesia", "editorial", "festival"],
        "descripcion": "Festival y colectivo de poesía del Valle de Aburrá. Convoca poetas de los 10 municipios metropolitanos en ciclos anuales.",
        "descripcion_corta": "Festival de poesía del Valle de Aburrá",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "poetasdelaburra",
        "nivel_actividad": "activo",
    },

    # ── FOTOGRAFÍA ──────────────────────────────────────────────────────
    {
        "nombre": "Lente Colectivo",
        "slug": "lente-colectivo-mde",
        "tipo": "colectivo",
        "categoria_principal": "fotografia",
        "categorias": ["fotografia", "galeria"],
        "descripcion": "Fotografía callejera y retrato documental en Medellín. Photo walks mensuales, exposiciones colectivas y crítica de imagen.",
        "descripcion_corta": "Fotografía callejera y retrato documental en Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "lentecolectivomde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Archivo Barrial",
        "slug": "archivo-barrial-mde",
        "tipo": "colectivo",
        "categoria_principal": "fotografia",
        "categorias": ["fotografia", "editorial", "muralismo"],
        "descripcion": "Proyecto de memoria visual barrial. Rescata fotografías históricas de comunidades populares del nororiente y occidente de Medellín.",
        "descripcion_corta": "Memoria visual y fotografías históricas de barrios de Medellín",
        "municipio": "medellin",
        "barrio": "Santa Cruz",
        "instagram_handle": "archivobarialmde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Polaroid Colectivo",
        "slug": "polaroid-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "fotografia",
        "categorias": ["fotografia", "galeria"],
        "descripcion": "Fotografía analógica y Polaroid. Talleres de cuarto oscuro, revelado y exposiciones de fotografía en película.",
        "descripcion_corta": "Fotografía analógica y cuarto oscuro en Medellín",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "polaroidcolectivo",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Foto Documental Comunas",
        "slug": "foto-documental-comunas",
        "tipo": "colectivo",
        "categoria_principal": "fotografia",
        "categorias": ["fotografia", "galeria", "cine"],
        "descripcion": "Fotografía documental en comunas populares de Medellín. Talleres de imagen con jóvenes, proyectos colectivos y exposiciones comunitarias.",
        "descripcion_corta": "Fotografía documental con jóvenes en comunas populares",
        "municipio": "medellin",
        "barrio": "Popular",
        "instagram_handle": "fotodocomunas",
        "nivel_actividad": "activo",
    },

    # ── CIRCO / ARTES AÉREAS ───────────────────────────────────────────
    {
        "nombre": "Aéreos Medellín",
        "slug": "aereos-medellin",
        "tipo": "colectivo",
        "categoria_principal": "circo",
        "categorias": ["circo", "danza", "teatro"],
        "descripcion": "Escuela y compañía de artes aéreas. Telas, trapecio, aro aéreo y acrobacia en tela. Espectáculos en parques y teatros del Valle de Aburrá.",
        "descripcion_corta": "Artes aéreas: telas, trapecio y aro en Medellín",
        "municipio": "medellin",
        "barrio": "Belén",
        "instagram_handle": "alineosmedellin",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Malabaristas del Aburrá",
        "slug": "malabaristas-del-aburra",
        "tipo": "colectivo",
        "categoria_principal": "circo",
        "categorias": ["circo", "festival"],
        "descripcion": "Red de malabaristas y artistas circenses del Valle de Aburrá. Encuentros en semáforos, parques y festivales callejeros.",
        "descripcion_corta": "Malabaristas y artistas circenses en el Valle de Aburrá",
        "municipio": "medellin",
        "barrio": "Robledo",
        "instagram_handle": "malabaristasva",
        "nivel_actividad": "moderado",
        "es_underground": True,
    },
    {
        "nombre": "Circo Ambulante Comunas",
        "slug": "circo-ambulante-comunas",
        "tipo": "colectivo",
        "categoria_principal": "circo",
        "categorias": ["circo", "teatro", "casa_cultura"],
        "descripcion": "Circo social como herramienta pedagógica en comunas de Medellín. Formación circense gratuita para niños y jóvenes.",
        "descripcion_corta": "Circo social y pedagogía en comunas de Medellín",
        "municipio": "medellin",
        "barrio": "San Javier",
        "instagram_handle": "circoambulantecomunas",
        "nivel_actividad": "activo",
    },

    # ── ARTE CONTEMPORÁNEO / PERFORMANCE ────────────────────────────────
    {
        "nombre": "Performancero MDE",
        "slug": "performancero-mde",
        "tipo": "colectivo",
        "categoria_principal": "arte_contemporaneo",
        "categorias": ["arte_contemporaneo", "teatro"],
        "descripcion": "Festival y colectivo de performance art en Medellín. Acciones artísticas, body art y performance político en espacios públicos.",
        "descripcion_corta": "Performance art y acciones artísticas en espacios públicos",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "performanceromde",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Laboratorio de Arte MDE",
        "slug": "laboratorio-arte-mde",
        "tipo": "colectivo",
        "categoria_principal": "arte_contemporaneo",
        "categorias": ["arte_contemporaneo", "galeria", "editorial"],
        "descripcion": "Espacio experimental de investigación y creación artística. Residencias, crítica de arte, videoarte e instalaciones.",
        "descripcion_corta": "Investigación y creación artística experimental",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "labartemed",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Arte Digital Antioquia",
        "slug": "arte-digital-antioquia",
        "tipo": "colectivo",
        "categoria_principal": "arte_contemporaneo",
        "categorias": ["arte_contemporaneo", "electronica"],
        "descripcion": "Arte generativo, net art y nuevos medios. Exhibiciones de arte digital, mapping y realidad aumentada en espacios alternativos.",
        "descripcion_corta": "Arte generativo, mapping y nuevos medios",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "artedigitalantioquia",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Colectivo Frontera Arte",
        "slug": "colectivo-frontera-arte",
        "tipo": "colectivo",
        "categoria_principal": "arte_contemporaneo",
        "categorias": ["arte_contemporaneo", "galeria", "muralismo"],
        "descripcion": "Arte en las fronteras: creación en zonas de conflicto y transformación urbana. Intervenciones en periferias de Medellín.",
        "descripcion_corta": "Arte en periferias y zonas de transformación urbana",
        "municipio": "medellin",
        "barrio": "Manrique",
        "instagram_handle": "fronteraartemde",
        "nivel_actividad": "moderado",
    },

    # ── DANZA ──────────────────────────────────────────────────────────
    {
        "nombre": "Danza Folclórica Andina MDE",
        "slug": "danza-folclorica-andina-mde",
        "tipo": "colectivo",
        "categoria_principal": "danza",
        "categorias": ["danza", "festival", "musica_en_vivo"],
        "descripcion": "Grupo de danza folclórica andina colombiana. Bambuco, torbellino y danzas de la región. Presentaciones en fiestas y festivales.",
        "descripcion_corta": "Danza folclórica andina: bambuco, torbellino y más",
        "municipio": "medellin",
        "barrio": "Castilla",
        "instagram_handle": "danzafolcloricamde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Salsa Afro Medellín",
        "slug": "salsa-afro-medellin",
        "tipo": "colectivo",
        "categoria_principal": "danza",
        "categorias": ["danza", "musica_en_vivo"],
        "descripcion": "Danza afro-colombiana y salsa caleña. Clases abiertas, performances callejeros y conexión con la comunidad afro del Valle de Aburrá.",
        "descripcion_corta": "Salsa caleña y danza afro-colombiana en Medellín",
        "municipio": "medellin",
        "barrio": "Guayabal",
        "instagram_handle": "salsaafromde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Contact Improv MDE",
        "slug": "contact-improv-mde",
        "tipo": "colectivo",
        "categoria_principal": "danza",
        "categorias": ["danza", "circo"],
        "descripcion": "Práctica de contact improvisation y danza somática. Jams abiertos semanales, talleres y encuentros de movimiento libre.",
        "descripcion_corta": "Contact improvisation y jams de movimiento libre",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "contactimprovmde",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Ballet Contemporáneo del Norte",
        "slug": "ballet-contemporaneo-del-norte",
        "tipo": "colectivo",
        "categoria_principal": "danza",
        "categorias": ["danza", "teatro"],
        "descripcion": "Compañía de danza clásica y contemporánea del nororiente de Medellín. Formación gratuita para jóvenes de comunas 1-4.",
        "descripcion_corta": "Danza clásica y contemporánea en comunas del nororiente",
        "municipio": "medellin",
        "barrio": "Popular",
        "instagram_handle": "balletcontemporanonorte",
        "nivel_actividad": "activo",
    },

    # ── TEATRO ────────────────────────────────────────────────────────
    {
        "nombre": "Teatro Comunitario San Javier",
        "slug": "teatro-comunitario-san-javier",
        "tipo": "colectivo",
        "categoria_principal": "teatro",
        "categorias": ["teatro", "danza", "musica_en_vivo"],
        "descripcion": "Teatro comunitario y popular en la Comuna 13. Obras sobre memoria, resistencia y vida cotidiana del barrio.",
        "descripcion_corta": "Teatro popular y memoria en la Comuna 13",
        "municipio": "medellin",
        "barrio": "San Javier",
        "instagram_handle": "teatrocomsanjavier",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Dramaturgia Joven MDE",
        "slug": "dramaturgia-joven-mde",
        "tipo": "colectivo",
        "categoria_principal": "teatro",
        "categorias": ["teatro", "editorial"],
        "descripcion": "Colectivo de dramaturgos emergentes de Medellín. Escritura de obras, dramaturgias breves y publicación de textos dramáticos.",
        "descripcion_corta": "Dramaturgos emergentes y publicación de obras",
        "municipio": "medellin",
        "barrio": "Buenos Aires",
        "instagram_handle": "dramaturgiajovenmed",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Teatro del Oprimido Medellín",
        "slug": "teatro-oprimido-medellin",
        "tipo": "colectivo",
        "categoria_principal": "teatro",
        "categorias": ["teatro", "casa_cultura"],
        "descripcion": "Metodología del Teatro del Oprimido de Boal. Trabajo con comunidades vulnerables, migrantes y víctimas del conflicto en Medellín.",
        "descripcion_corta": "Teatro del Oprimido con comunidades vulnerables",
        "municipio": "medellin",
        "barrio": "Manrique",
        "instagram_handle": "teatrooprimidomed",
        "nivel_actividad": "activo",
    },

    # ── HIP HOP / URBANO ──────────────────────────────────────────────
    {
        "nombre": "Escuela de Hip Hop Nororiental",
        "slug": "escuela-hiphop-nororiental",
        "tipo": "colectivo",
        "categoria_principal": "hip_hop",
        "categorias": ["hip_hop", "danza", "muralismo"],
        "descripcion": "Escuela gratuita de hip-hop en el nororiente de Medellín. MC, DJ, breaking y graffiti para jóvenes de las comunas 1, 2 y 3.",
        "descripcion_corta": "Hip-hop gratuito para jóvenes del nororiente",
        "municipio": "medellin",
        "barrio": "Popular",
        "instagram_handle": "escuelahiphopnorte",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Rap Terapéutico MDE",
        "slug": "rap-terapeutico-mde",
        "tipo": "colectivo",
        "categoria_principal": "hip_hop",
        "categorias": ["hip_hop", "poesia", "casa_cultura"],
        "descripcion": "Rap como herramienta terapéutica y de resiliencia. Talleres con jóvenes víctimas del conflicto y en riesgo de exclusión social.",
        "descripcion_corta": "Rap terapéutico con jóvenes en situación de vulnerabilidad",
        "municipio": "medellin",
        "barrio": "San Javier",
        "instagram_handle": "rapterapeuticomde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Liga de Freestyle Aburrá",
        "slug": "liga-freestyle-aburra",
        "tipo": "colectivo",
        "categoria_principal": "batalla_freestyle",
        "categorias": ["batalla_freestyle", "hip_hop"],
        "descripcion": "Liga metropolitana de batallas de freestyle. Competencias clasificatorias en todos los municipios del Valle de Aburrá.",
        "descripcion_corta": "Liga metropolitana de batallas de freestyle",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "ligafreestyleaburra",
        "nivel_actividad": "muy_activo",
    },

    # ── MURALISMO / ARTE URBANO ───────────────────────────────────────
    {
        "nombre": "Mural Festival MDE",
        "slug": "mural-festival-mde",
        "tipo": "colectivo",
        "categoria_principal": "muralismo",
        "categorias": ["muralismo", "festival", "galeria"],
        "descripcion": "Festival anual de muralismo en el Centro de Medellín. Artistas nacionales e internacionales transforman fachadas del centro histórico.",
        "descripcion_corta": "Festival anual de murales en el Centro de Medellín",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "muralfestivalmde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Graffiti Comuna 13",
        "slug": "graffiti-comuna-13",
        "tipo": "colectivo",
        "categoria_principal": "muralismo",
        "categorias": ["muralismo", "hip_hop", "turismo"],
        "descripcion": "Colectivo de graffiti y arte urbano de la Comuna 13. Murales de memoria y paz. Guías de los tours de graffiti más conocidos de la ciudad.",
        "descripcion_corta": "Graffiti de memoria y paz en la Comuna 13",
        "municipio": "medellin",
        "barrio": "San Javier",
        "lat": 6.2492,
        "lng": -75.6072,
        "instagram_handle": "graffiti_c13",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Pincel Libre Colectivo",
        "slug": "pincel-libre-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "muralismo",
        "categorias": ["muralismo", "galeria"],
        "descripcion": "Pintura mural y arte callejero en Belén y el occidente de Medellín. Intervenciones en espacios públicos y fachadas comunitarias.",
        "descripcion_corta": "Pintura mural y arte callejero en el occidente de Medellín",
        "municipio": "medellin",
        "barrio": "Belén",
        "instagram_handle": "pincellibreco",
        "nivel_actividad": "activo",
    },

    # ── MÚSICA EN VIVO / INDEPENDIENTE ───────────────────────────────
    {
        "nombre": "Rock Independiente MDE",
        "slug": "rock-independiente-mde",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival"],
        "descripcion": "Red de bandas de rock independiente de Medellín. Conciertos en bares, festivales underground y apoyo a bandas emergentes.",
        "descripcion_corta": "Rock independiente: conciertos y festivales underground",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "rockindependientemde",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Metal Sin Fronteras",
        "slug": "metal-sin-fronteras-mde",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival"],
        "descripcion": "Colectivo de metal extremo en Medellín. Conciertos de death metal, black metal y doom en recintos alternativos.",
        "descripcion_corta": "Metal extremo en recintos alternativos de Medellín",
        "municipio": "medellin",
        "barrio": "Prado",
        "instagram_handle": "metalsinfronterasmde",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Folk & Raíces Antioquia",
        "slug": "folk-raices-antioquia",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival"],
        "descripcion": "Música folk, andina y de raíces campesinas de Antioquia. Tiples, bandolas y voces en encuentros de música tradicional.",
        "descripcion_corta": "Folk andino y música campesina de Antioquia",
        "municipio": "medellin",
        "barrio": "Buenos Aires",
        "instagram_handle": "folkraicesantioquia",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Punk Medellín",
        "slug": "punk-medellin-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival", "editorial"],
        "descripcion": "Escena punk y hardcore de Medellín. Conciertos, fanzines, DIY y autogestión cultural desde los barrios populares.",
        "descripcion_corta": "Punk, hardcore y DIY en Medellín",
        "municipio": "medellin",
        "barrio": "Robledo",
        "instagram_handle": "punkmedellin",
        "nivel_actividad": "activo",
        "es_underground": True,
    },

    # ── MUNICIPIOS VALLE DE ABURRÁ ────────────────────────────────────
    {
        "nombre": "Caldas Cultural",
        "slug": "caldas-cultural-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "teatro", "musica_en_vivo"],
        "descripcion": "Colectivo artístico del municipio de Caldas. Teatro, música y artes plásticas para la comunidad del sur del Valle de Aburrá.",
        "descripcion_corta": "Arte y cultura comunitaria en Caldas",
        "municipio": "caldas",
        "barrio": "Centro",
        "instagram_handle": "caldascultural",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Barbosa Vive",
        "slug": "barbosa-vive-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "musica_en_vivo", "danza"],
        "descripcion": "Colectivo cultural de Barbosa. Gestión artística comunitaria, música folclórica y eventos culturales en el norte del Aburrá.",
        "descripcion_corta": "Gestión cultural comunitaria en Barbosa",
        "municipio": "barbosa",
        "barrio": "Centro",
        "instagram_handle": "barbosavive",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Girardota Creativa",
        "slug": "girardota-creativa",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "teatro", "festival"],
        "descripcion": "Colectivo de artes escénicas y gestión cultural de Girardota. Festivales locales, teatro y talleres artísticos.",
        "descripcion_corta": "Artes escénicas y festivales en Girardota",
        "municipio": "girardota",
        "barrio": "Centro",
        "instagram_handle": "girardotacreativa",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "Retiro Arte & Naturaleza",
        "slug": "retiro-arte-naturaleza",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "festival", "fotografia"],
        "descripcion": "Arte y naturaleza en El Retiro. Instalaciones al aire libre, land art y festivales de fotografía en paisajes de las afueras del Aburrá.",
        "descripcion_corta": "Land art y fotografía en los paisajes de El Retiro",
        "municipio": "el_retiro",
        "barrio": "Centro",
        "instagram_handle": "retiroartenaturaleza",
        "nivel_actividad": "moderado",
    },
    {
        "nombre": "La Ceja Suena",
        "slug": "la-ceja-suena",
        "tipo": "colectivo",
        "categoria_principal": "musica_en_vivo",
        "categorias": ["musica_en_vivo", "festival"],
        "descripcion": "Escena musical de La Ceja Antioquia. Bandas emergentes, festivales locales y conciertos en el parque central.",
        "descripcion_corta": "Música en vivo y festivales en La Ceja",
        "municipio": "la_ceja",
        "barrio": "Centro",
        "instagram_handle": "lacejasuena",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Rionegro Cultura Viva",
        "slug": "rionegro-cultura-viva",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "teatro", "galeria", "musica_en_vivo"],
        "descripcion": "Red cultural de Rionegro. Articulación de artistas, gestores y espacios en el Oriente Antioqueño.",
        "descripcion_corta": "Red cultural y artística de Rionegro",
        "municipio": "rionegro",
        "barrio": "Centro",
        "instagram_handle": "rionegrocultureviva",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Marinilla Arte",
        "slug": "marinilla-arte-colectivo",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "festival", "editorial"],
        "descripcion": "Arte y cultura en Marinilla. Exposiciones de artistas locales, ferias culturales y publicaciones sobre el Oriente Antioqueño.",
        "descripcion_corta": "Arte y cultura en Marinilla, Oriente Antioqueño",
        "municipio": "marinilla",
        "barrio": "Centro",
        "instagram_handle": "marinillaarte",
        "nivel_actividad": "moderado",
    },

    # ── CINE / AUDIOVISUAL ────────────────────────────────────────────
    {
        "nombre": "Cineclub Universitario MDE",
        "slug": "cineclub-universitario-mde",
        "tipo": "colectivo",
        "categoria_principal": "cine",
        "categorias": ["cine", "editorial"],
        "descripcion": "Cineclub con ciclos temáticos de cine mundial, latinoamericano y colombiano. Foros, análisis fílmico y publicación de textos de crítica.",
        "descripcion_corta": "Cineclub con ciclos temáticos y crítica fílmica",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "cineclubuniversitariomde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Documental Comunal",
        "slug": "documental-comunal-mde",
        "tipo": "colectivo",
        "categoria_principal": "cine",
        "categorias": ["cine", "fotografia", "editorial"],
        "descripcion": "Producción de documentales comunitarios en barrios de Medellín. Narrativas desde adentro sobre memoria, conflicto y transformación.",
        "descripcion_corta": "Documentales comunitarios desde las comunas de Medellín",
        "municipio": "medellin",
        "barrio": "Manrique",
        "instagram_handle": "documentalcomunalmde",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Festival de Cine Corto Aburrá",
        "slug": "festival-cine-corto-aburra",
        "tipo": "colectivo",
        "categoria_principal": "cine",
        "categorias": ["cine", "festival"],
        "descripcion": "Festival de cortometrajes del Valle de Aburrá. Convocatoria abierta a realizadores locales y latinoamericanos.",
        "descripcion_corta": "Festival de cortometrajes del Valle de Aburrá",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "festcinecortoaburra",
        "nivel_actividad": "activo",
    },

    # ── ELECTRÓNICA / EXPERIMENTACIÓN ─────────────────────────────────
    {
        "nombre": "Techno Colectivo MDE",
        "slug": "techno-colectivo-mde",
        "tipo": "colectivo",
        "categoria_principal": "electronica",
        "categorias": ["electronica", "musica_en_vivo"],
        "descripcion": "Techno y música de club en Medellín. Fiestas en almacenes, parqueaderos y espacios no convencionales. No comercial.",
        "descripcion_corta": "Techno underground en espacios no convencionales",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "tecnocolectivomde",
        "nivel_actividad": "muy_activo",
        "es_underground": True,
    },
    {
        "nombre": "Síntesis Modular MDE",
        "slug": "sintesis-modular-mde",
        "tipo": "colectivo",
        "categoria_principal": "electronica",
        "categorias": ["electronica", "arte_contemporaneo"],
        "descripcion": "Comunidad de síntesis modular y música generativa. Talleres de Eurorack, patching, instalaciones sonoras y jam sessions electrónicas.",
        "descripcion_corta": "Síntesis modular y música generativa en Medellín",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "sinmodularmde",
        "nivel_actividad": "activo",
        "es_underground": True,
    },
    {
        "nombre": "Ambient & Drones MDE",
        "slug": "ambient-drones-mde",
        "tipo": "colectivo",
        "categoria_principal": "electronica",
        "categorias": ["electronica", "arte_contemporaneo"],
        "descripcion": "Música ambient, drone y paisajes sonoros. Conciertos en la oscuridad, instalaciones sonoras y sesiones de escucha activa.",
        "descripcion_corta": "Ambient, drone y paisajes sonoros en Medellín",
        "municipio": "medellin",
        "barrio": "Carlos E. Restrepo",
        "instagram_handle": "ambientdronesmde",
        "nivel_actividad": "moderado",
        "es_underground": True,
    },

    # ── GASTRONOMÍA CULTURAL / MERCADOS ────────────────────────────────
    {
        "nombre": "Mercado Cultural del Centro",
        "slug": "mercado-cultural-centro-mde",
        "tipo": "colectivo",
        "categoria_principal": "espacio_hibrido",
        "categorias": ["espacio_hibrido", "galeria", "musica_en_vivo"],
        "descripcion": "Mercado de arte, artesanía, música y comida. Domingo a domingo en el Centro de Medellín. Más de 80 expositores locales.",
        "descripcion_corta": "Mercado de arte, artesanía y música en el Centro",
        "municipio": "medellin",
        "barrio": "Centro",
        "instagram_handle": "mercadoculturalcentromde",
        "nivel_actividad": "muy_activo",
    },
    {
        "nombre": "Arrabal Mercado Creativo",
        "slug": "arrabal-mercado-creativo",
        "tipo": "colectivo",
        "categoria_principal": "espacio_hibrido",
        "categorias": ["espacio_hibrido", "galeria", "editorial"],
        "descripcion": "Mercado de diseño, arte y emprendimiento creativo en Laureles. Diseñadores independientes, artistas visuales y editoriales pequeñas.",
        "descripcion_corta": "Diseño, arte y emprendimiento creativo en Laureles",
        "municipio": "medellin",
        "barrio": "Laureles",
        "instagram_handle": "arrabalmercado",
        "nivel_actividad": "activo",
    },

    # ── DIVERSIDAD / COMUNIDADES ──────────────────────────────────────
    {
        "nombre": "Arte Diverso MDE",
        "slug": "arte-diverso-mde",
        "tipo": "colectivo",
        "categoria_principal": "espacio_hibrido",
        "categorias": ["espacio_hibrido", "teatro", "galeria"],
        "descripcion": "Arte y cultura desde la diversidad sexual y de género. Obras, exposiciones y eventos que visibilizan la comunidad LGBTIQ+ de Medellín.",
        "descripcion_corta": "Arte y cultura desde la diversidad LGBTIQ+ en Medellín",
        "municipio": "medellin",
        "barrio": "El Poblado",
        "instagram_handle": "artediversomde",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Afrocolombia Cultural Aburrá",
        "slug": "afrocolombia-cultural-aburra",
        "tipo": "colectivo",
        "categoria_principal": "casa_cultura",
        "categorias": ["casa_cultura", "musica_en_vivo", "danza"],
        "descripcion": "Preservación y difusión de las culturas afrocolombianas en el Valle de Aburrá. Música del Pacífico, danza, gastronomía y oralidad.",
        "descripcion_corta": "Culturas afrocolombianas: música, danza y oralidad",
        "municipio": "medellin",
        "barrio": "Guayabal",
        "instagram_handle": "afrocolombiaculturalab",
        "nivel_actividad": "activo",
    },
    {
        "nombre": "Tejido de Mujeres Artistas",
        "slug": "tejido-mujeres-artistas",
        "tipo": "colectivo",
        "categoria_principal": "galeria",
        "categorias": ["galeria", "editorial", "poesia"],
        "descripcion": "Red de artistas, escritoras y gestoras culturales. Exposiciones feministas, publicaciones y residencias artísticas en Medellín.",
        "descripcion_corta": "Red de mujeres artistas, escritoras y gestoras culturales",
        "municipio": "medellin",
        "barrio": "Buenos Aires",
        "instagram_handle": "tejidomujeresartistas",
        "nivel_actividad": "activo",
    },
]

inserted = 0
skipped = 0
errors = 0
for col in colectivos:
    try:
        existing = supabase.table("lugares").select("id").eq("slug", col["slug"]).execute()
        if existing.data:
            print(f"  Skip: {col['nombre']}")
            skipped += 1
            continue
        supabase.table("lugares").insert(col).execute()
        print(f"  OK: {col['nombre']}")
        inserted += 1
    except Exception as e:
        print(f"  ERROR {col['nombre']}: {e}")
        errors += 1

print(f"\nDone! Inserted: {inserted}, Skipped: {skipped}, Errors: {errors}")
