# -*- coding: utf-8 -*-
"""
Seed data — Colectivos y cuentas culturales del Valle de Aburrá.
Incluye perfiles locales para monitoreo activo (eventos, flyers)
y cuentas nacionales/internacionales de referencia.
"""

# ═══════════════════════════════════════════════════════════════
# SEMILLA ORIGINAL — colectivos base conocidos
# ═══════════════════════════════════════════════════════════════
SEMILLA = [
    # ── TEATRO ──
    {"nombre": "Teatro El Trueque", "handle": "@teatroeltrueque", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Corporación Teatral Hora 25", "handle": "@hora25teatro", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Teatro Matacandelas", "handle": "@teatromatacandelas", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Teatro El Pequeño", "handle": "@teatroelpequeno", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Casa del Teatro de Medellín", "handle": "@casadelteatromed", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Teatro Popular de Medellín", "handle": "@teatropopularmed", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Corporación Artística La Polilla", "handle": "@lapolillateatro", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Teatro Oficina Central de los Sueños", "handle": "@oficinacentralsuenos", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Corporación Arca de Noé", "handle": "@arcadenoe_teatro", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Ziruma Teatro", "handle": "@zirumateatro", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},

    # ── MÚSICA ──
    {"nombre": "Colectivo Musical Medellín", "handle": "@colectivomusicalmed", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Red de Escuelas de Música de Medellín", "handle": "@redmusicamedellin", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Altavoz Fest", "handle": "@altavozfest", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Medellín Jazz Festival", "handle": "@medellinjazzfest", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Colectivo Hip Hop Medellín", "handle": "@hiphopmed", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Corporación Son Batá", "handle": "@sonbata", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Revolución Sin Muertos", "handle": "@revolucionsinmuertos", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},

    # ── LITERATURA ──
    {"nombre": "Festival Internacional de Poesía de Medellín", "handle": "@festivalpoesiamed", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Fiesta del Libro y la Cultura", "handle": "@fiabordecultura", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Corporación Prometeo", "handle": "@corporacionprometeo", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Tragaluz Editores", "handle": "@tragaluzeditores", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Sílaba Editores", "handle": "@silabaeditores", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Editorial EAFIT", "handle": "@editorialeafit", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Club de Lectura Medellín", "handle": "@clublecturamedellin", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Biblioteca Pública Piloto", "handle": "@babordemedellin", "plataforma": "instagram",
     "categoria": "literatura", "municipio": "Medellín", "fuente": "semilla"},

    # ── FILOSOFÍA ──
    {"nombre": "Café Filosófico de Medellín", "handle": "@cafefilosoficomedellin", "plataforma": "instagram",
     "categoria": "filosofia", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Estanislao Zuleta Fundación", "handle": "@fundacionezuleta", "plataforma": "instagram",
     "categoria": "filosofia", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Instituto de Filosofía UdeA", "handle": "@filosofiaudea", "plataforma": "instagram",
     "categoria": "filosofia", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Filosofía en la Calle", "handle": "@filosofiaenlacalle", "plataforma": "instagram",
     "categoria": "filosofia", "municipio": "Medellín", "fuente": "semilla"},

    # ── ARTE GENERAL / GESTIÓN CULTURAL ──
    {"nombre": "Casa Tres Patios", "handle": "@casatrespatios", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Museo de Antioquia", "handle": "@museodeantioquia", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Museo de Arte Moderno de Medellín", "handle": "@mamabordemedellin", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Parque Explora", "handle": "@parabordeexplora", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Corporación Cultural Nuestra Gente", "handle": "@nuestragente", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "La Pascasia", "handle": "@lapascasia", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Colectivo Morada", "handle": "@colectivomorada", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Platohedro", "handle": "@platohedro", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Corporación Región", "handle": "@corporacionregion", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Comfama Cultura", "handle": "@comfama", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Colectivo Visible", "handle": "@colectivovisible", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},

    # ── OTROS MUNICIPIOS ──
    {"nombre": "Casa de la Cultura de Envigado", "handle": "@culturenvigado", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Envigado", "fuente": "semilla"},
    {"nombre": "Casa de la Cultura de Bello", "handle": "@culturabello", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Bello", "fuente": "semilla"},
    {"nombre": "Casa de la Cultura de Itagüí", "handle": "@culturaitagui", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Itagüí", "fuente": "semilla"},
    {"nombre": "Casa de la Cultura de Sabaneta", "handle": "@culturasabaneta", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Sabaneta", "fuente": "semilla"},

    # ── PRIORITY HANDLES (superprompt v2) ──
    # Hip-hop y cultura urbana
    {"nombre": "Crew Peligrosos", "handle": "@crewpeligrosos", "plataforma": "instagram",
     "categoria": "hip_hop", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "4 Elementos Skuela", "handle": "@4elementosskuela", "plataforma": "instagram",
     "categoria": "hip_hop", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Batallas de Medellín", "handle": "@batallasdemedellin", "plataforma": "instagram",
     "categoria": "hip_hop", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Combate MDE", "handle": "@combate_mde", "plataforma": "instagram",
     "categoria": "hip_hop", "municipio": "Medellín", "fuente": "semilla"},

    # Teatro adicional
    {"nombre": "Teatro Pórtico", "handle": "@teatroportico", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Águila Descalza", "handle": "@aguiladescalza", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "El Montacargas", "handle": "@elmontacargas", "plataforma": "instagram",
     "categoria": "teatro", "municipio": "Medellín", "fuente": "semilla"},

    # Música independiente
    {"nombre": "Club del Jazz", "handle": "@elclubdeljazz", "plataforma": "instagram",
     "categoria": "jazz", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Portón Sound", "handle": "@portonsound", "plataforma": "instagram",
     "categoria": "musica", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Club Eléctrico MDE", "handle": "@clubelectrico_mde", "plataforma": "instagram",
     "categoria": "electronica", "municipio": "Medellín", "fuente": "semilla"},

    # Arte contemporáneo y galerías
    {"nombre": "Casa Nubes Galería", "handle": "@casanubesgaleria", "plataforma": "instagram",
     "categoria": "galeria", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Galería Borrero", "handle": "@galeriaborero", "plataforma": "instagram",
     "categoria": "galeria", "municipio": "Medellín", "fuente": "semilla"},

    # Literatura y filosofía
    {"nombre": "Otraparte", "handle": "@otraparte_medellin", "plataforma": "instagram",
     "categoria": "filosofia", "municipio": "Envigado", "fuente": "semilla"},
    {"nombre": "Palinuro Librería Café", "handle": "@palinurolibreriacafe", "plataforma": "instagram",
     "categoria": "libreria", "municipio": "Medellín", "fuente": "semilla"},

    # Festivales
    {"nombre": "Circo La Minga", "handle": "@circolaminga", "plataforma": "instagram",
     "categoria": "circo", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Festival de Cine Colombia", "handle": "@festivalcinecolombia", "plataforma": "instagram",
     "categoria": "cine", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Miradas Medellín", "handle": "@miradasmedellin", "plataforma": "instagram",
     "categoria": "cine", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Festival de Tango", "handle": "@festivaldetangomedellin", "plataforma": "instagram",
     "categoria": "danza", "municipio": "Medellín", "fuente": "semilla"},

    # Cultura comunitaria
    {"nombre": "Centro Cultural Moravia", "handle": "@centroculturalmoravia", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
    {"nombre": "Compás Urbano", "handle": "@compasurbano", "plataforma": "instagram",
     "categoria": "arte_general", "municipio": "Medellín", "fuente": "semilla"},
]


# ═══════════════════════════════════════════════════════════════
# RED CULTURAL COMPLETA — Perfiles de Instagram verificados
# Clasificados por tipo y prioridad de monitoreo
# ═══════════════════════════════════════════════════════════════

# Prioridad: "alta" = scraping frecuente (organizan eventos)
#            "media" = scraping periódico (publican agenda)
#            "baja" = scraping semanal (referencia/inspiración)
#            "solo_referencia" = no scrapear, solo para enriquecer búsquedas

# ── MUSEOS (agenda de exposiciones, talleres, eventos) ────────
MUSEOS = [
    {"handle": "@museodeantioquia", "nombre": "Museo de Antioquia", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 118091, "prioridad": "alta"},
    {"handle": "@elmamm", "nombre": "MAMM - Museo de Arte Moderno de Medellín", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 187389, "prioridad": "alta"},
    {"handle": "@museocasadelamemoria.med", "nombre": "Museo Casa de la Memoria", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 60438, "prioridad": "alta"},
    {"handle": "@museobiciclasicas", "nombre": "Museo Biciclasicas & Antiguas", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 20674, "prioridad": "media"},
    {"handle": "@murock.medellin", "nombre": "Museo Rock Medellín", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 2672, "prioridad": "media"},
    {"handle": "@camera_shelf", "nombre": "Camera Museum", "categoria": "fotografia",
     "municipio": None, "seguidores": 12365, "prioridad": "solo_referencia"},
    {"handle": "@museo_del_rock", "nombre": "Rock Infinito Museo", "categoria": "musica",
     "municipio": None, "seguidores": 106, "prioridad": "solo_referencia"},
    {"handle": "@museoresistencia", "nombre": "Museo De la Resistencia", "categoria": "arte_general",
     "municipio": None, "seguidores": 15, "prioridad": "solo_referencia"},
    {"handle": "@ratona_de_museo", "nombre": "Carolina Avendaño Echeverri", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1825, "prioridad": "baja"},
    # Nacionales
    {"handle": "@museonacionalco", "nombre": "Museo Nacional de Colombia", "categoria": "arte_general",
     "municipio": None, "seguidores": 149245, "prioridad": "solo_referencia"},
    {"handle": "@mambogota", "nombre": "MAMBO Bogotá", "categoria": "arte_general",
     "municipio": None, "seguidores": 146983, "prioridad": "solo_referencia"},
    {"handle": "@museodeloro", "nombre": "Museo del Oro de Colombia", "categoria": "arte_general",
     "municipio": None, "seguidores": 100582, "prioridad": "solo_referencia"},
    {"handle": "@museoscolombianos", "nombre": "Prog. Fortalecimiento Museos", "categoria": "arte_general",
     "municipio": None, "seguidores": 6453, "prioridad": "solo_referencia"},
]

# ── TEATROS (agenda de obras, temporadas, talleres) ──────────
TEATROS = [
    {"handle": "@teatropablotobon", "nombre": "Teatro Pablo Tobón Uribe", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 100600, "prioridad": "alta"},
    {"handle": "@pequeno_teatrom", "nombre": "Pequeño Teatro de Medellín", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 60308, "prioridad": "alta"},
    {"handle": "@teatroprado", "nombre": "Teatro Prado", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 47326, "prioridad": "alta"},
    {"handle": "@teatrometropolitano", "nombre": "Teatro Metropolitano José Gutiérrez", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 78258, "prioridad": "alta"},
    {"handle": "@corporacionziruma", "nombre": "Corporación Ziruma Teatro", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 4056, "prioridad": "alta"},
    {"handle": "@casatallerteatro", "nombre": "CasaTallerTeatro", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 7146, "prioridad": "alta"},
    {"handle": "@elnidocultural", "nombre": "El Nido Café Cultural", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 13500, "prioridad": "alta"},
    {"handle": "@ateneomedellin", "nombre": "Ateneo Porfirio Barba Jacob", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 22153, "prioridad": "alta"},
    {"handle": "@teatroelnombre", "nombre": "Teatro el Nombre", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 2810, "prioridad": "media"},
    {"handle": "@mararayteatro", "nombre": "Grupo Mararay", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 3072, "prioridad": "media"},
    {"handle": "@ruateatro", "nombre": "RÚA Teatro", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 676, "prioridad": "media"},
    {"handle": "@anaelvira.teatro", "nombre": "ELVIRA Teatro", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 726, "prioridad": "baja"},
    {"handle": "@ellas_teatro", "nombre": "Ellas Teatro", "categoria": "teatro",
     "municipio": "Medellín", "seguidores": 4, "prioridad": "baja"},
    {"handle": "@teatrotoscobogota", "nombre": "Teatro Tosco", "categoria": "teatro",
     "municipio": None, "seguidores": 2357, "prioridad": "solo_referencia"},
]

# ── MÚSICA (artistas locales, bandas, productoras, orquestas) ─
MUSICA = [
    {"handle": "@filarmed", "nombre": "Orquesta Filarmónica de Medellín", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 61010, "prioridad": "alta"},
    {"handle": "@festivalaltavozmed", "nombre": "Festival Altavoz", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 74950, "prioridad": "alta"},
    {"handle": "@recorridorockero", "nombre": "Recorrido Cultural Rockero Medellín", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 6727, "prioridad": "alta"},
    {"handle": "@procesoculturalelhormiguero", "nombre": "El Hormiguero", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 5141, "prioridad": "alta"},
    {"handle": "@voltaestudio", "nombre": "VOLTA ESTUDIO Producción Musical", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 10111, "prioridad": "media"},
    {"handle": "@parchebanda", "nombre": "Parche Banda", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 19062, "prioridad": "media"},
    {"handle": "@adabellamusic", "nombre": "Adabella", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 6931, "prioridad": "media"},
    {"handle": "@estefaniaalvarezmusica", "nombre": "Estefania Álvarez", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 5112, "prioridad": "media"},
    {"handle": "@balbomusic_", "nombre": "Balbo", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 3376, "prioridad": "media"},
    {"handle": "@alejandrosantamusica", "nombre": "Alejandro Santa", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 3227, "prioridad": "media"},
    {"handle": "@mateomadmusic", "nombre": "Mateo Mad Music", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 2297, "prioridad": "media"},
    {"handle": "@palaciomusic", "nombre": "Christian Palacio", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1907, "prioridad": "media"},
    {"handle": "@migueloc.music", "nombre": "Miguel Angel Ortega", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1367, "prioridad": "baja"},
    {"handle": "@avemontesmusica", "nombre": "Ave Montes", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1237, "prioridad": "baja"},
    {"handle": "@este.musica", "nombre": "ESTE", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 863, "prioridad": "baja"},
    {"handle": "@valenc.music", "nombre": "Valentina", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 719, "prioridad": "baja"},
    {"handle": "@uncuartomusic", "nombre": "Un Cuarto", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 711, "prioridad": "baja"},
    {"handle": "@agnemakesmusic", "nombre": "Agnemakesmusic", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 202, "prioridad": "baja"},
    {"handle": "@lelomusica", "nombre": "LELO", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 14243, "prioridad": "media"},
    {"handle": "@popcornmusica", "nombre": "Popcorn Musica", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 7447, "prioridad": "media"},
    {"handle": "@alibombomusica", "nombre": "Alibombo", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 4765, "prioridad": "media"},
    {"handle": "@callevagamusica", "nombre": "CalleVaga y Los Animales Fumadores", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 2486, "prioridad": "media"},
    {"handle": "@uhlalamusica", "nombre": "Uh lalá", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 2407, "prioridad": "baja"},
    {"handle": "@sebastianmejia_musica", "nombre": "Sebastian Mejia", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 2207, "prioridad": "baja"},
    {"handle": "@luna_caustica", "nombre": "Luna Cáustica", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 3186, "prioridad": "media"},
    {"handle": "@lacuerdaflojamusica", "nombre": "La Cuerda Floja", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 343, "prioridad": "baja"},
    {"handle": "@lira_musica", "nombre": "LIRA", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 2117, "prioridad": "baja"},
    {"handle": "@casi.musica", "nombre": "Casi", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 8777, "prioridad": "media"},
    {"handle": "@camilorestrepomusica", "nombre": "Camilo Restrepo", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 11776, "prioridad": "media"},
    {"handle": "@reynermusica", "nombre": "REYNER", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1964, "prioridad": "baja"},
    {"handle": "@therivermanmusic", "nombre": "The Riverman", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1905, "prioridad": "baja"},
    {"handle": "@weekendfriendmusic", "nombre": "WEEKEND FRIEND", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 6107, "prioridad": "media"},
    {"handle": "@tiagogsmusic", "nombre": "Tiago GS", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1466, "prioridad": "baja"},
    {"handle": "@felowmusic", "nombre": "FELOW", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 882, "prioridad": "baja"},
    {"handle": "@flipmusicstudio", "nombre": "FLIP", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1111, "prioridad": "baja"},
    {"handle": "@maycruz_music", "nombre": "May", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1230, "prioridad": "baja"},
    {"handle": "@cooperwhitemusic", "nombre": "Cooper White", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1386, "prioridad": "baja"},
    {"handle": "@vlunemusic", "nombre": "Val", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 489, "prioridad": "baja"},
    {"handle": "@elvismusician", "nombre": "ELVIS", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 153, "prioridad": "baja"},
    {"handle": "@inefablemusicc", "nombre": "INEFABLE MUSIC", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 525, "prioridad": "media"},
    {"handle": "@comunidad_red_", "nombre": "Red de Músicas de Medellín", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 514, "prioridad": "media"},
    {"handle": "@hd_producciones.eventosmusica", "nombre": "HD Producciones", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 765, "prioridad": "media"},
    {"handle": "@viajeros_musica", "nombre": "VIAJEROS", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 226, "prioridad": "baja"},
    {"handle": "@rapsodiabanda", "nombre": "Rapsodia Band", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 224, "prioridad": "baja"},
    {"handle": "@sushymusic", "nombre": "Sushy", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 677, "prioridad": "baja"},
    {"handle": "@un_tal_sherik", "nombre": "Música Negra", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 589, "prioridad": "baja"},
    {"handle": "@3pilares.musical", "nombre": "3 Pilares", "categoria": "musica",
     "municipio": None, "seguidores": 85212, "prioridad": "solo_referencia"},
    {"handle": "@caroramirezmusic", "nombre": "Carolina Ramirez", "categoria": "musica",
     "municipio": None, "seguidores": 16282, "prioridad": "solo_referencia"},
    {"handle": "@jaelmusica", "nombre": "JAEL", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 17091, "prioridad": "media"},
    {"handle": "@latomamusic", "nombre": "La Toma", "categoria": "musica",
     "municipio": None, "seguidores": 26700, "prioridad": "solo_referencia"},
    {"handle": "@mitumusic", "nombre": "MITÚ", "categoria": "musica",
     "municipio": None, "seguidores": 28095, "prioridad": "solo_referencia"},
    {"handle": "@juandasmusic", "nombre": "Juandas", "categoria": "musica",
     "municipio": None, "seguidores": 112918, "prioridad": "solo_referencia"},
    {"handle": "@lamare_musica", "nombre": "La Mare", "categoria": "musica",
     "municipio": None, "seguidores": 47549, "prioridad": "solo_referencia"},
    {"handle": "@delaporte.music", "nombre": "Delaporte", "categoria": "musica",
     "municipio": None, "seguidores": 89484, "prioridad": "solo_referencia"},
    {"handle": "@martagomezmusic", "nombre": "Marta Gómez", "categoria": "musica",
     "municipio": None, "seguidores": 157433, "prioridad": "solo_referencia"},
    {"handle": "@marasoulmusic", "nombre": "MaraSoul", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1746, "prioridad": "baja"},
    {"handle": "@lyricsco2", "nombre": "LyricsMusicCo", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 670, "prioridad": "baja"},
    {"handle": "@puertos_prohibidosbanda", "nombre": "Puertos Prohibidos", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 2536, "prioridad": "media"},
    {"handle": "@gonorreadebanda", "nombre": "Gonorrea de Banda", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 720, "prioridad": "baja"},
    {"handle": "@anhedoniabanda", "nombre": "Anhedonia", "categoria": "musica",
     "municipio": None, "seguidores": 1152, "prioridad": "solo_referencia"},
    {"handle": "@eonbanda", "nombre": "En Obra Negra", "categoria": "musica",
     "municipio": "Itagüí", "seguidores": 69, "prioridad": "baja"},
    {"handle": "@etereo_banda", "nombre": "ETEREO", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 108, "prioridad": "baja"},
    {"handle": "@liraensamblevocal", "nombre": "Lira Ensamble Vocal", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 40, "prioridad": "baja"},
    {"handle": "@adorartepereira", "nombre": "Escuela de Música Adorarte", "categoria": "musica",
     "municipio": None, "seguidores": 8194, "prioridad": "solo_referencia"},
]

# ── CINE Y AUDIOVISUAL ───────────────────────────────────────
CINE = [
    {"handle": "@cinematecademedellin", "nombre": "Cinemateca de Medellín", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 20734, "prioridad": "alta"},
    {"handle": "@cinemanciafestival", "nombre": "CINEMANCIA Festival", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 9181, "prioridad": "alta"},
    {"handle": "@mfantasmagoria", "nombre": "Festival Fantasmagoría", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 16111, "prioridad": "alta"},
    {"handle": "@incinerante_fest", "nombre": "Incinerante Fest", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 1946, "prioridad": "alta"},
    {"handle": "@camaraenmanocineclub", "nombre": "Cámara en Mano Cineclub", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 22450, "prioridad": "alta"},
    {"handle": "@coocine_", "nombre": "COOCINE Cooperativa de Cine", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 5135, "prioridad": "alta"},
    {"handle": "@casadelsol.corporaciondecine", "nombre": "CNCCS", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 2493, "prioridad": "media"},
    {"handle": "@art_poetic_cinema", "nombre": "Art Poetic Cinema", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 2232, "prioridad": "media"},
    {"handle": "@mediodecontencionproducciones", "nombre": "Medio de Contención Producciones", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 6051, "prioridad": "media"},
    {"handle": "@dantacine", "nombre": "Danta Cine", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 14143, "prioridad": "media"},
    {"handle": "@raracolectivo", "nombre": "Rara Cine", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 6573, "prioridad": "media"},
    {"handle": "@rueda_libre_cine", "nombre": "Rueda Libre Cine", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 1712, "prioridad": "media"},
    {"handle": "@divididoscolectivo", "nombre": "DIVIDIDOS Colectivo Audiovisual", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 624, "prioridad": "media"},
    {"handle": "@lacolinitacine", "nombre": "K-1000 A", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 2771, "prioridad": "baja"},
    {"handle": "@cine_rodante", "nombre": "Cine Rodante", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 248, "prioridad": "baja"},
    {"handle": "@cineclubUtopia", "nombre": "Cine Club Utopia Latinoamericana", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 1019, "prioridad": "media"},
    {"handle": "@cinecolocal", "nombre": "cineCOLocal", "categoria": "cine",
     "municipio": None, "seguidores": 5554, "prioridad": "solo_referencia"},
    {"handle": "@iisavisual", "nombre": "Fotografía y Cine", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 196, "prioridad": "baja"},
    {"handle": "@espacio.filmico", "nombre": "Espacio Fílmico", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 166, "prioridad": "baja"},
    {"handle": "@prod98_cine", "nombre": "Producción 98", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 213, "prioridad": "baja"},
    {"handle": "@malejamira", "nombre": "Malejalonda Audiovisual", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 243, "prioridad": "baja"},
    {"handle": "@reofotografia", "nombre": "REO FILMS", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 4263, "prioridad": "baja"},
    {"handle": "@rojisha_ph", "nombre": "ROJA FOTOGRAFÍA", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 325, "prioridad": "baja"},
    {"handle": "@patfilmcolombia", "nombre": "Patrimonio Fílmico Colombiano", "categoria": "cine",
     "municipio": None, "seguidores": 41802, "prioridad": "solo_referencia"},
    {"handle": "@juanita_ospina_", "nombre": "Realizadora Audiovisual", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 5150, "prioridad": "baja"},
    {"handle": "@marka.audiovisual", "nombre": "Marka Audiovisual", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 3303, "prioridad": "baja"},
    {"handle": "@bsalbage", "nombre": "Brian Steven Audiovisual", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 301, "prioridad": "baja"},
    # Nacionales/internacionales referencia
    {"handle": "@cinematecabta", "nombre": "Cinemateca de Bogotá", "categoria": "cine",
     "municipio": None, "seguidores": 153792, "prioridad": "solo_referencia"},
    {"handle": "@cinetecanacionalcl", "nombre": "Cineteca Nacional de Chile", "categoria": "cine",
     "municipio": None, "seguidores": 166063, "prioridad": "solo_referencia"},
    {"handle": "@cinecropsia", "nombre": "Esteban Muñoz", "categoria": "cine",
     "municipio": None, "seguidores": 151920, "prioridad": "solo_referencia"},
]

# ── FOTOGRAFÍA ────────────────────────────────────────────────
FOTOGRAFIA = [
    {"handle": "@fotografiapaisajismoyretrato", "nombre": "Jose Miguel Fotografía", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 2170, "prioridad": "baja"},
    {"handle": "@cafera13", "nombre": "Cafera Fotografía", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 17404, "prioridad": "media"},
    {"handle": "@imperioanalogo", "nombre": "Fotografía Tangible", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 12925, "prioridad": "media"},
    {"handle": "@analogos_colombianos", "nombre": "Fotografía Análoga Colombia", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 4205, "prioridad": "media"},
    {"handle": "@flaneur_analogico", "nombre": "Flâneur Analógico Lab", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 93, "prioridad": "baja"},
    {"handle": "@hugogris.estudio", "nombre": "Hugo Gris Estudio", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 342, "prioridad": "baja"},
    {"handle": "@antioquiaenfotografias", "nombre": "Antioquia en Fotografías", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 42021, "prioridad": "media"},
    {"handle": "@eninfoco", "nombre": "Encuentro Investigadores Fotografía Colombia", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 278, "prioridad": "media"},
    {"handle": "@comunidadanalogica", "nombre": "Comunidad Analógica", "categoria": "fotografia",
     "municipio": None, "seguidores": 30131, "prioridad": "solo_referencia"},
    {"handle": "@tragaluzfotografia", "nombre": "TRAGALUZ FOTOGRAFIA", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 2337, "prioridad": "baja"},
    {"handle": "@dannoverfotografia", "nombre": "Dannover Arroyave", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 1053, "prioridad": "baja"},
    {"handle": "@clementina.fotografia", "nombre": "Clementina", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 4284, "prioridad": "baja"},
    {"handle": "@43mmfotografia", "nombre": "Mateo Monsalve Montoya", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 2678, "prioridad": "baja"},
    {"handle": "@nando_f05", "nombre": "Nando Fotografía", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 780, "prioridad": "baja"},
    {"handle": "@ojodemono_ft", "nombre": "Ojo de Mono Fotografía", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 506, "prioridad": "baja"},
    {"handle": "@luzartesanal__", "nombre": "Alejandra Arroyave Fotografía", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 353, "prioridad": "baja"},
    {"handle": "@daniel_q881", "nombre": "Fotografía Daniel Q", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 1728, "prioridad": "baja"},
    {"handle": "@agenciacolectivaamalias", "nombre": "Amalias Colectiva Fotógrafas", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 3209, "prioridad": "media"},
    {"handle": "@buenrollo.cali", "nombre": "Buen Rollo Fotografía Análoga", "categoria": "fotografia",
     "municipio": None, "seguidores": 5592, "prioridad": "solo_referencia"},
    {"handle": "@lauradiosafotografia", "nombre": "Laura Fotografía Documental", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 7146, "prioridad": "baja"},
    {"handle": "@fotografosetenta7", "nombre": "Team Setenta 7 Fotografía", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 2497, "prioridad": "baja"},
    {"handle": "@alejarivaph", "nombre": "Alejandra Rivera Fotografía y Video", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 1862, "prioridad": "baja"},
]

# ── LITERATURA Y POESÍA ──────────────────────────────────────
LITERATURA = [
    {"handle": "@gustavoliteratura", "nombre": "Gustavo Adolfo", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 8233, "prioridad": "media"},
    {"handle": "@casadepoesiasilva", "nombre": "Casa de Poesía Silva", "categoria": "literatura",
     "municipio": None, "seguidores": 13530, "prioridad": "solo_referencia"},
    {"handle": "@podcastpoesia", "nombre": "Poesía Podcast", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 369, "prioridad": "baja"},
    {"handle": "@podcast_poesia", "nombre": "La Coleccionista de Azules Podcast", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 106, "prioridad": "baja"},
    {"handle": "@alejo.literario", "nombre": "A Fuego Literario", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 496, "prioridad": "baja"},
    {"handle": "@gacetaelgaleon", "nombre": "Gaceta Literaria El Galeón", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 1224, "prioridad": "media"},
    {"handle": "@eslilacupb", "nombre": "Semillero Estudios Literarios UPB", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 427, "prioridad": "media"},
    {"handle": "@literaturaeneafit", "nombre": "Literatura en EAFIT", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 2769, "prioridad": "media"},
    {"handle": "@mentorliterariogrunge555", "nombre": "Juan Bedoya", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 161, "prioridad": "baja"},
    {"handle": "@perpetuaescritura_", "nombre": "Perpetua Escritura", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 12495, "prioridad": "media"},
    {"handle": "@lab_tramadera", "nombre": "Colectivo Lab Tramadera", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 116, "prioridad": "baja"},
    {"handle": "@madameglue_", "nombre": "Madame Glue Collage Literario", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 554, "prioridad": "media"},
    {"handle": "@altazorescrituracreativa", "nombre": "Taller Altazor Escritura Creativa", "categoria": "literatura",
     "municipio": None, "seguidores": 37098, "prioridad": "solo_referencia"},
    {"handle": "@literatura.paravivir", "nombre": "Literatura para Vivir", "categoria": "literatura",
     "municipio": None, "seguidores": 108902, "prioridad": "solo_referencia"},
    {"handle": "@entereflexivo", "nombre": "Entereflexivo Literatura", "categoria": "literatura",
     "municipio": None, "seguidores": 315109, "prioridad": "solo_referencia"},
    {"handle": "@la.escritura.es.cultura", "nombre": "La Escritura es Cultura", "categoria": "literatura",
     "municipio": None, "seguidores": 539830, "prioridad": "solo_referencia"},
    {"handle": "@literaturayletras", "nombre": "Laura Maestre", "categoria": "literatura",
     "municipio": None, "seguidores": 29572, "prioridad": "solo_referencia"},
    {"handle": "@lenguayliteraturaprofesor", "nombre": "Lengua y Literatura Profesor", "categoria": "literatura",
     "municipio": None, "seguidores": 12408, "prioridad": "solo_referencia"},
    {"handle": "@relatos_literarios_", "nombre": "Cultura con Lectura", "categoria": "literatura",
     "municipio": None, "seguidores": 4858, "prioridad": "solo_referencia"},
    {"handle": "@talleresimaginarios", "nombre": "Talleres Imaginarios", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 229, "prioridad": "media"},
]

# ── EDITORIALES Y PUBLICACIONES ───────────────────────────────
EDITORIALES = [
    {"handle": "@laprotestaeditorial", "nombre": "La Protesta", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 235, "prioridad": "media"},
    {"handle": "@animalextintoeditorial", "nombre": "Animal Extinto Editorial", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 6768, "prioridad": "media"},
    {"handle": "@colectivo_editorial_mutante", "nombre": "Colectivo Editorial Mutante", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 8493, "prioridad": "media"},
    {"handle": "@tristestropicosed", "nombre": "Tristes Trópicos Editorial", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 3990, "prioridad": "media"},
    {"handle": "@bitacoraeafit", "nombre": "Revista Bitácora EAFIT", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 2396, "prioridad": "media"},
    {"handle": "@pensamientohumanista", "nombre": "Revista Pensamiento Humanista", "categoria": "filosofia",
     "municipio": "Medellín", "seguidores": 719, "prioridad": "media"},
    {"handle": "@generacion_revista", "nombre": "Revista Generación", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 5135, "prioridad": "media"},
    {"handle": "@revkinetoscopio", "nombre": "Revista Kinetoscopio", "categoria": "cine",
     "municipio": "Medellín", "seguidores": 11648, "prioridad": "media"},
    {"handle": "@cultura_1913", "nombre": "Cultura de Cancha", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3770, "prioridad": "baja"},
    {"handle": "@editorial_plo", "nombre": "Pablo Suazo Arancibia", "categoria": "literatura",
     "municipio": None, "seguidores": 9180, "prioridad": "solo_referencia"},
    {"handle": "@palabraherida", "nombre": "Editorial Palabra Herida", "categoria": "literatura",
     "municipio": None, "seguidores": 100245, "prioridad": "solo_referencia"},
    {"handle": "@letrasnegrascolombia", "nombre": "Letras Negras Colombia", "categoria": "literatura",
     "municipio": None, "seguidores": 36466, "prioridad": "solo_referencia"},
    {"handle": "@grupoeditorialletrasnegras", "nombre": "Grupo Editorial Letras Negras", "categoria": "literatura",
     "municipio": None, "seguidores": 18945, "prioridad": "solo_referencia"},
    {"handle": "@transitoeditorial", "nombre": "Editorial Tránsito", "categoria": "literatura",
     "municipio": None, "seguidores": 26554, "prioridad": "solo_referencia"},
    {"handle": "@letrameeditorial", "nombre": "Letrame Grupo Editorial", "categoria": "literatura",
     "municipio": None, "seguidores": 53057, "prioridad": "solo_referencia"},
    {"handle": "@ita_editorial", "nombre": "ITA Editorial", "categoria": "literatura",
     "municipio": None, "seguidores": 92636, "prioridad": "solo_referencia"},
    {"handle": "@gacetarevista", "nombre": "GACETA Revista", "categoria": "arte_general",
     "municipio": None, "seguidores": 27905, "prioridad": "solo_referencia"},
    {"handle": "@paredropodcast", "nombre": "Paredro Podcast", "categoria": "literatura",
     "municipio": None, "seguidores": 18286, "prioridad": "solo_referencia"},
    {"handle": "@archivo909", "nombre": "Archivo909", "categoria": "arte_general",
     "municipio": None, "seguidores": 536010, "prioridad": "solo_referencia"},
    {"handle": "@revista_hekatombe", "nombre": "Revista Hekatombe", "categoria": "arte_general",
     "municipio": None, "seguidores": 98576, "prioridad": "solo_referencia"},
    {"handle": "@revistaplaylist", "nombre": "Revista Playlist", "categoria": "musica",
     "municipio": None, "seguidores": 56739, "prioridad": "solo_referencia"},
    {"handle": "@puntoo.y.aparte", "nombre": "Cami Puntoyaparte", "categoria": "literatura",
     "municipio": None, "seguidores": 116636, "prioridad": "solo_referencia"},
    {"handle": "@natgeolatam", "nombre": "National Geographic Latam", "categoria": "arte_general",
     "municipio": None, "seguidores": 941285, "prioridad": "solo_referencia"},
    {"handle": "@revistapaulachile", "nombre": "Revista Paula", "categoria": "arte_general",
     "municipio": None, "seguidores": 243452, "prioridad": "solo_referencia"},
    {"handle": "@revistaanfibia", "nombre": "Revista Anfibia", "categoria": "arte_general",
     "municipio": None, "seguidores": 449273, "prioridad": "solo_referencia"},
]

# ── FUNDACIONES Y CORPORACIONES ───────────────────────────────
FUNDACIONES = [
    {"handle": "@somosfundacionhuellas", "nombre": "Fundación Huellas Medellín", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1681, "prioridad": "media"},
    {"handle": "@tuhuellafundacion", "nombre": "Tu Huella Tienda", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 161, "prioridad": "baja"},
    {"handle": "@ekobots", "nombre": "EKO BOTS Corporación", "categoria": "arte_general",
     "municipio": None, "seguidores": 554, "prioridad": "solo_referencia"},
    {"handle": "@territorios.creativos", "nombre": "Corporación Territorios Creativos", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 507, "prioridad": "media"},
    {"handle": "@corporacionaequus", "nombre": "CorpoAequus", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 185, "prioridad": "baja"},
    {"handle": "@fundacionteresadecalcuta", "nombre": "Fundación Teresa de Calcuta", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 169, "prioridad": "baja"},
    {"handle": "@fundaciongabo", "nombre": "Fundación Gabo", "categoria": "literatura",
     "municipio": None, "seguidores": 66063, "prioridad": "solo_referencia"},
    {"handle": "@festivalgabo", "nombre": "Festival Gabo", "categoria": "arte_general",
     "municipio": None, "seguidores": 23563, "prioridad": "solo_referencia"},
    {"handle": "@fundaciongrupoepm", "nombre": "Fundación Grupo EPM", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 35406, "prioridad": "alta"},
    {"handle": "@fundacionorca", "nombre": "Fundación ORCA", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 46113, "prioridad": "baja"},
    {"handle": "@corpregion", "nombre": "Corporación Región", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 4590, "prioridad": "media"},
    {"handle": "@corpodh_jesusmariavalle", "nombre": "Corporación DDHH Jesús María Valle", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1259, "prioridad": "baja"},
    {"handle": "@corpojuridicalibertad", "nombre": "Corporación Jurídica Libertad", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 5569, "prioridad": "baja"},
    {"handle": "@gustavoddhh", "nombre": "Corporación Gustavo Marulanda", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 325, "prioridad": "baja"},
    {"handle": "@circodelarua", "nombre": "Circo de la Rúa", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3331, "prioridad": "media"},
    {"handle": "@fundacionlasgolondrinas", "nombre": "Fundación Las Golondrinas", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 10443, "prioridad": "media"},
    {"handle": "@somosantivirus", "nombre": "Fundación Antivirus FATV", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3317, "prioridad": "baja"},
    {"handle": "@fundacionpianissimo", "nombre": "Fundación Pianissimo", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 8211, "prioridad": "media"},
    {"handle": "@secretosparacontar", "nombre": "Fundación Secretos para Contar", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 7968, "prioridad": "media"},
    {"handle": "@fundacion.gratitud", "nombre": "Fundación Gratitud", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 4595, "prioridad": "media"},
    {"handle": "@fundacionmontanitadecolores", "nombre": "Fundación Montañita de Colores", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1939, "prioridad": "baja"},
    {"handle": "@feslic_fundacion", "nombre": "Feslic Fundación Festival del Libro", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 55, "prioridad": "media"},
    {"handle": "@fecisla", "nombre": "FECISLA Corporación", "categoria": "cine",
     "municipio": None, "seguidores": 4895, "prioridad": "solo_referencia"},
    {"handle": "@altavistacorpo", "nombre": "Corporación Cultural Altavista", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2170, "prioridad": "media"},
    {"handle": "@ccorcrear", "nombre": "Corporación CORCREAR", "categoria": "arte_general",
     "municipio": "Bello", "seguidores": 855, "prioridad": "media"},
    {"handle": "@corporacionbalurdo", "nombre": "Corporación Balurdo", "categoria": "arte_general",
     "municipio": None, "seguidores": 202, "prioridad": "baja"},
    {"handle": "@corporacionclubrotarioitagui", "nombre": "Club Rotario Itagüí", "categoria": "arte_general",
     "municipio": "Itagüí", "seguidores": 1656, "prioridad": "baja"},
    {"handle": "@cafe.fundacion", "nombre": "Café Fundación", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 34883, "prioridad": "media"},
    {"handle": "@gdc.fundacion", "nombre": "Fundación Gente de Gran Corazón", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1815, "prioridad": "baja"},
    {"handle": "@corporacionflorpurpura", "nombre": "Corporación Flor Púrpura", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2367, "prioridad": "media"},
]

# ── COLECTIVOS ────────────────────────────────────────────────
COLECTIVOS = [
    {"handle": "@la_disonancia", "nombre": "Colectiva Disonancia Gráfica", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 763, "prioridad": "media"},
    {"handle": "@siclas", "nombre": "Colectivo SiCLas", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 16432, "prioridad": "media"},
    {"handle": "@theinsidersco", "nombre": "The Insiders Collective", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 19676, "prioridad": "alta"},
    {"handle": "@reojocolectivo", "nombre": "Reojo Colectivo", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 5552, "prioridad": "media"},
    {"handle": "@photolab_ph", "nombre": "PhotoLab Colectivo", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 177, "prioridad": "baja"},
    {"handle": "@colectivobc25", "nombre": "COLECTIVO ESTUDIANTIL BC25", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2049, "prioridad": "baja"},
    {"handle": "@colectivo_afro", "nombre": "COLECTIVO AFRO UPB", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 573, "prioridad": "baja"},
    {"handle": "@mythoscolectivo", "nombre": "Mythos Colectivo", "categoria": "literatura",
     "municipio": "Medellín", "seguidores": 563, "prioridad": "media"},
    {"handle": "@red.accion.colectivo", "nombre": "RedAcción", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1078, "prioridad": "baja"},
    {"handle": "@cayoarteycultura", "nombre": "CAYO Colectivo Artístico", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1056, "prioridad": "media"},
    {"handle": "@nucleo_colectivo_art", "nombre": "NÚCLEO COLECTIVO", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 48, "prioridad": "baja"},
    {"handle": "@colectivo_de_ruedas", "nombre": "Colectivo Deportes Extremos C9", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 111, "prioridad": "baja"},
    {"handle": "@fauvecolectivo", "nombre": "Fauve Colectivo", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 63, "prioridad": "baja"},
    {"handle": "@elpincel_colectivo", "nombre": "El Pincel Colectivo", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 59, "prioridad": "baja"},
    {"handle": "@colectivo.la.resistencia.maipu", "nombre": "Colectivo La Resistencia", "categoria": "arte_general",
     "municipio": None, "seguidores": 47, "prioridad": "baja"},
    {"handle": "@marabunta_colectivx", "nombre": "Marabunta Colectivx", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 170, "prioridad": "baja"},
    {"handle": "@bcncollective", "nombre": "BCN Collective", "categoria": "fotografia",
     "municipio": None, "seguidores": 75656, "prioridad": "solo_referencia"},
]

# ── GALERÍAS ──────────────────────────────────────────────────
GALERIAS = [
    {"handle": "@galeriacarlosorozco", "nombre": "Galería Carlos Orozco", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 6388, "prioridad": "alta"},
    {"handle": "@unojocomungaleria", "nombre": "Galería Un Ojo Común", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3768, "prioridad": "alta"},
    {"handle": "@bunkergaleria", "nombre": "Búnker Galería", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3129, "prioridad": "alta"},
    {"handle": "@imagenexpandidaarte", "nombre": "Imagen Expandida Virtual Gallery", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 49, "prioridad": "baja"},
    {"handle": "@sibilartgallery", "nombre": "Sibilart Gallery", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 58, "prioridad": "baja"},
    {"handle": "@historyof.art_", "nombre": "Sue's Gallery", "categoria": "arte_general",
     "municipio": None, "seguidores": 470729, "prioridad": "solo_referencia"},
    {"handle": "@streetgallerymagazine", "nombre": "Street Photography Hub", "categoria": "fotografia",
     "municipio": None, "seguidores": 38239, "prioridad": "solo_referencia"},
    {"handle": "@georgsgallery", "nombre": "Georg Petermandl", "categoria": "arte_general",
     "municipio": None, "seguidores": 141017, "prioridad": "solo_referencia"},
    {"handle": "@gallerymoryta", "nombre": "Gallery MORYTA", "categoria": "arte_general",
     "municipio": None, "seguidores": 18766, "prioridad": "solo_referencia"},
    {"handle": "@academic_drawing_school", "nombre": "Academic Drawing School", "categoria": "arte_general",
     "municipio": None, "seguidores": 201361, "prioridad": "solo_referencia"},
]

# ── FESTIVALES ────────────────────────────────────────────────
FESTIVALES = [
    {"handle": "@comfamacultura", "nombre": "Comfama Cultura", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 101766, "prioridad": "alta"},
    {"handle": "@tesiturasfestival", "nombre": "Festival Tesituras", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 493, "prioridad": "alta"},
    {"handle": "@adrianmusica", "nombre": "Sambe Rock Festival", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 4040, "prioridad": "alta"},
    {"handle": "@radiorageoficial", "nombre": "Radio Rage", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 4311, "prioridad": "media"},
    {"handle": "@festereopicnic", "nombre": "Festival Estéreo Picnic", "categoria": "musica",
     "municipio": None, "seguidores": 439171, "prioridad": "solo_referencia"},
    {"handle": "@cordillerafestival", "nombre": "Festival Cordillera", "categoria": "musica",
     "municipio": None, "seguidores": 166144, "prioridad": "solo_referencia"},
]

# ── ESPACIOS CULTURALES, CAFÉS, CENTROS ──────────────────────
ESPACIOS_CULTURALES = [
    {"handle": "@otraparte", "nombre": "Otraparte", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 44991, "prioridad": "alta"},
    {"handle": "@bibliotecaotraparte", "nombre": "Biblioteca Otraparte", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 24440, "prioridad": "alta"},
    {"handle": "@salonprado.med", "nombre": "Salón Prado", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 21729, "prioridad": "alta"},
    {"handle": "@ortografikka", "nombre": "Centro Cultural Ortográfika", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 22911, "prioridad": "alta"},
    {"handle": "@latrillacultural", "nombre": "Parche Cultural La Trilla", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 17260, "prioridad": "alta"},
    {"handle": "@cafeclichebistro", "nombre": "Café Cliché Medellín", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 28216, "prioridad": "alta"},
    {"handle": "@lacatedralcafecultural", "nombre": "La Catedral Café Cultural", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 14308, "prioridad": "alta"},
    {"handle": "@indeleblecafecultural", "nombre": "Indeleble Café Cultural", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 6314, "prioridad": "alta"},
    {"handle": "@faunocafecultural", "nombre": "Fauno Café Cultural", "categoria": "arte_general",
     "municipio": "Envigado", "seguidores": 6218, "prioridad": "alta"},
    {"handle": "@centroculturalmoravia", "nombre": "Centro Cultural de Moravia", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 10581, "prioridad": "alta"},
    {"handle": "@lacasacentro", "nombre": "La Casa Centro Cultural", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 12657, "prioridad": "alta"},
    {"handle": "@cdcelpoblado", "nombre": "Casa de Cultura El Poblado", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 4435, "prioridad": "alta"},
    {"handle": "@centrobomarzo", "nombre": "Centro Bomarzo", "categoria": "arte_general",
     "municipio": None, "seguidores": 2932, "prioridad": "media"},
    {"handle": "@laplantamedellin", "nombre": "La Planta Cervecería", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 23698, "prioridad": "media"},
]

# ── ORGANIZACIONES CULTURALES INSTITUCIONALES ─────────────────
INSTITUCIONALES = [
    {"handle": "@cultura.med", "nombre": "Cultura Ciudadana Alcaldía Medellín", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 100980, "prioridad": "alta"},
    {"handle": "@udeacultura", "nombre": "UdeA Cultura", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 43455, "prioridad": "alta"},
    {"handle": "@culturantioquia", "nombre": "ICPA Instituto Cultura Antioquia", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 32471, "prioridad": "alta"},
    {"handle": "@patrimoniomde", "nombre": "Memorias y Patrimonio Medellín", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 10005, "prioridad": "alta"},
    {"handle": "@banrepcultural", "nombre": "Banrepcultural", "categoria": "arte_general",
     "municipio": None, "seguidores": 248629, "prioridad": "solo_referencia"},
    {"handle": "@avhmedellin", "nombre": "Instituto Alexander von Humboldt", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 5125, "prioridad": "media"},
    {"handle": "@culturaeafit", "nombre": "Extensión Cultural EAFIT", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3770, "prioridad": "alta"},
    {"handle": "@artesyhumanidades.eafit", "nombre": "Artes y Humanidades EAFIT", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3289, "prioridad": "media"},
    {"handle": "@upb_bibliotecaycultura", "nombre": "Libros Arte y Cultura UPB", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3726, "prioridad": "media"},
    {"handle": "@escueladeadministracioneafit", "nombre": "Escuela Administración EAFIT", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3232, "prioridad": "baja"},
    {"handle": "@artehum.uniandes", "nombre": "Artes y Humanidades Uniandes", "categoria": "arte_general",
     "municipio": None, "seguidores": 23393, "prioridad": "solo_referencia"},
    {"handle": "@facultad_artesyhumanidades", "nombre": "FAH Mi Facultad UdeCaldas", "categoria": "arte_general",
     "municipio": None, "seguidores": 6335, "prioridad": "solo_referencia"},
    {"handle": "@artesyhumanidadesitm", "nombre": "Artes y Humanidades ITM", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 4706, "prioridad": "media"},
    {"handle": "@asamblea_artes_udea", "nombre": "Asamblea Fac. Artes UdeA", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 977, "prioridad": "media"},
    {"handle": "@escuelaalcine", "nombre": "Programa Escuela al Cine", "categoria": "cine",
     "municipio": None, "seguidores": 20804, "prioridad": "solo_referencia"},
    {"handle": "@lamcultural", "nombre": "La Movida Cultural", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 4310, "prioridad": "alta"},
    {"handle": "@culturalmenar", "nombre": "Corporación Cultural Almenar", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 386, "prioridad": "media"},
]

# ── RADIO Y PODCASTS ──────────────────────────────────────────
RADIO_PODCASTS = [
    {"handle": "@laesquinaradio", "nombre": "La Esquina Radio 101.4 FM", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3216, "prioridad": "media"},
    {"handle": "@radiolatente", "nombre": "Radio Latente", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 690, "prioridad": "baja"},
    {"handle": "@entrenosotrosyeldim", "nombre": "Podcast DIM", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2800, "prioridad": "baja"},
    {"handle": "@podcast.equis", "nombre": "Equis Podcast", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1319, "prioridad": "baja"},
    {"handle": "@radio.n.n", "nombre": "Radio NN", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 1545, "prioridad": "baja"},
    {"handle": "@nohaybanderasenmarte", "nombre": "No Hay Banderas en Marte", "categoria": "arte_general",
     "municipio": None, "seguidores": 172589, "prioridad": "solo_referencia"},
    {"handle": "@podcastlascosascomoson", "nombre": "Las Cosas Como Son", "categoria": "arte_general",
     "municipio": None, "seguidores": 171100, "prioridad": "solo_referencia"},
    {"handle": "@renegadoradio", "nombre": "Luis Gonzalez Renegado Radio", "categoria": "musica",
     "municipio": None, "seguidores": 208012, "prioridad": "solo_referencia"},
    {"handle": "@radiouniacc", "nombre": "Radio UNIACC", "categoria": "arte_general",
     "municipio": None, "seguidores": 10420, "prioridad": "solo_referencia"},
]

# ── DANZA ─────────────────────────────────────────────────────
DANZA = [
    {"handle": "@volare_danzaaerea", "nombre": "Volaré Danza Aérea", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 14435, "prioridad": "media"},
    {"handle": "@lostinthisdance", "nombre": "Danza A.", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 944, "prioridad": "baja"},
    {"handle": "@nesa_dancer", "nombre": "Vane Vargas Valencia", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1006, "prioridad": "baja"},
    {"handle": "@anamariamesalvarez", "nombre": "Ana María Mesa Biodanza", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 840, "prioridad": "baja"},
]

# ── ARTE, DISEÑO Y TALLERES ──────────────────────────────────
ARTE_DISENO = [
    {"handle": "@nodo.eafit", "nombre": "Nodo EAFIT", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 11140, "prioridad": "media"},
    {"handle": "@vilenafigueira", "nombre": "Vilena Figueira Activadora de Archivos", "categoria": "fotografia",
     "municipio": "Medellín", "seguidores": 7612, "prioridad": "media"},
    {"handle": "@culturalhacker1", "nombre": "Bernardo Galeano Bolívar", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1481, "prioridad": "media"},
    {"handle": "@somosartejoven", "nombre": "Somos Arte Joven", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1119, "prioridad": "media"},
    {"handle": "@intercultural.mentepsi", "nombre": "Psicóloga Nohemy Rengifo", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1105, "prioridad": "baja"},
    {"handle": "@_jhonatan.alexander_", "nombre": "Saldarriaga Registro y Diseño", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 977, "prioridad": "baja"},
    {"handle": "@lar_persot", "nombre": "Talleres Lar-Persot", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 309, "prioridad": "baja"},
    {"handle": "@taller.rabia", "nombre": "Taller Rabia", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 161, "prioridad": "baja"},
    {"handle": "@lapajarerataller", "nombre": "La Pajarera Taller", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1711, "prioridad": "baja"},
    {"handle": "@mci.ergo", "nombre": "Movimiento Cultural ERGO", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2177, "prioridad": "media"},
    {"handle": "@pineal.arte", "nombre": "Pineal Arte", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 4071, "prioridad": "baja"},
    {"handle": "@arte13.circo", "nombre": "Arte Trece Circo", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1152, "prioridad": "media"},
    {"handle": "@eterliteros", "nombre": "Éter Filosofía Poesía y Arte", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 57, "prioridad": "media"},
    {"handle": "@rinoarte.macrame", "nombre": "RinoArte Macramé", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1304, "prioridad": "baja"},
    {"handle": "@caballitodearte", "nombre": "Caballito de Arte", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3723, "prioridad": "baja"},
    {"handle": "@maar_arte", "nombre": "MAAR", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3347, "prioridad": "baja"},
    {"handle": "@isabelhenaoarte", "nombre": "Isabel Henao C.", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 592, "prioridad": "baja"},
    {"handle": "@marita.arte", "nombre": "Margarita María Taborda", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 145, "prioridad": "baja"},
    {"handle": "@male.arte", "nombre": "Maria Alejandra Baena", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2556, "prioridad": "baja"},
    {"handle": "@otraparte_szc", "nombre": "Sofía Zapata C", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 377, "prioridad": "baja"},
    {"handle": "@todaspartes_poemas", "nombre": "Islanada", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 63, "prioridad": "baja"},
    {"handle": "@lacasade.lula", "nombre": "La Casa de Lula", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3109, "prioridad": "media"},
    {"handle": "@mikicorfiel", "nombre": "Miki Programación Creativa", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3091, "prioridad": "baja"},
    {"handle": "@sevale.habitatcreativo", "nombre": "Arte Terapéutico Natalia Restrepo", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3119, "prioridad": "baja"},
    {"handle": "@transhumantecreative", "nombre": "Transhumante Creativo", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 815, "prioridad": "media"},
    {"handle": "@artesanintis", "nombre": "Inti Artesanías", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 347, "prioridad": "baja"},
    {"handle": "@khroma.oficial", "nombre": "Khroma Sellos y Libretas", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1452, "prioridad": "baja"},
    {"handle": "@mestiza.estudio", "nombre": "Mestiza Velas Artesanales", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2487, "prioridad": "baja"},
    {"handle": "@martesana__", "nombre": "Martesana Artesanías", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 317, "prioridad": "baja"},
    {"handle": "@aquije.grafico", "nombre": "Aquije Arte Gráfico", "categoria": "arte_general",
     "municipio": None, "seguidores": 12246, "prioridad": "solo_referencia"},
    {"handle": "@caroaduarte", "nombre": "Caro Duarte", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 428, "prioridad": "baja"},
    {"handle": "@ceartduart", "nombre": "César Duarte Higuita", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 445, "prioridad": "baja"},
    {"handle": "@estudio_praeesse", "nombre": "Carlos Martínez G", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 270, "prioridad": "baja"},
    {"handle": "@bazarartesurbanas", "nombre": "Bazar Artes Urbanas", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 271, "prioridad": "media"},
    {"handle": "@jose.artstudio", "nombre": "Jose F. Enriquez Arte y Diseño", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 192, "prioridad": "baja"},
    {"handle": "@suenodeartee", "nombre": "Agencia Creativa Sueño de Arte", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 162, "prioridad": "baja"},
    {"handle": "@on_ghee_artesanal", "nombre": "Olga Varela Machado", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 112, "prioridad": "baja"},
    {"handle": "@juan.cafe_taller", "nombre": "Juan David Gómez Café Taller", "categoria": "filosofia",
     "municipio": "Medellín", "seguidores": 804, "prioridad": "media"},
    # Diseño destacado
    {"handle": "@maratondg", "nombre": "Maratón Diseño Gráfico", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 3232, "prioridad": "baja"},
    {"handle": "@andreszorrilla", "nombre": "Andrés Zorrilla Diseño", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 2003, "prioridad": "baja"},
    {"handle": "@rolandodisenadorweb", "nombre": "Rolando Diseño Web", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 572, "prioridad": "baja"},
    # Gestión cultural
    {"handle": "@cumareconsultores", "nombre": "Cumare Consultores Culturales", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 609, "prioridad": "media"},
    {"handle": "@anamasso_lab", "nombre": "Ana Masso Proyectos Culturales", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1722, "prioridad": "media"},
    {"handle": "@lauriszapata_7", "nombre": "Lau Creativa", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 1467, "prioridad": "baja"},
    {"handle": "@somosmonoliebre", "nombre": "Monoliebre Producciones", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 4708, "prioridad": "media"},
    {"handle": "@soydelcarajo", "nombre": "Del Carajo Producciones", "categoria": "musica",
     "municipio": "Medellín", "seguidores": 3119, "prioridad": "media"},
    {"handle": "@estudiosie7eproducciones", "nombre": "Estudio Sie7e Producciones", "categoria": "arte_general",
     "municipio": "Medellín", "seguidores": 174, "prioridad": "baja"},
]

# ── CUENTAS INTERNACIONALES (solo referencia, no scrapear) ───
INTERNACIONALES_REF = [
    {"handle": "@culturainquieta", "nombre": "Cultura Inquieta", "seguidores": 5847837, "prioridad": "solo_referencia"},
    {"handle": "@nprmusic", "nombre": "NPR Music", "seguidores": 3571060, "prioridad": "solo_referencia"},
    {"handle": "@avant.arte", "nombre": "Avant Arte", "seguidores": 2911009, "prioridad": "solo_referencia"},
    {"handle": "@alcala.creativo", "nombre": "Juan Alcala", "seguidores": 2138509, "prioridad": "solo_referencia"},
    {"handle": "@cinematologist_", "nombre": "Cinematologist", "seguidores": 1777530, "prioridad": "solo_referencia"},
    {"handle": "@sensacine", "nombre": "SensaCine", "seguidores": 1742926, "prioridad": "solo_referencia"},
    {"handle": "@thelegendsofmusic", "nombre": "The Legends Of Music", "seguidores": 1608664, "prioridad": "solo_referencia"},
    {"handle": "@musicdiscoveryhour", "nombre": "Music Discovery Hour", "seguidores": 988717, "prioridad": "solo_referencia"},
    {"handle": "@photocinematica", "nombre": "Photo Cinematica", "seguidores": 760376, "prioridad": "solo_referencia"},
    {"handle": "@cinema.poetry", "nombre": "Cinema Poetry", "seguidores": 654107, "prioridad": "solo_referencia"},
    {"handle": "@sunomusic", "nombre": "Suno", "seguidores": 377518, "prioridad": "solo_referencia"},
    {"handle": "@pildoras_culturales", "nombre": "Píldoras Culturales", "seguidores": 397329, "prioridad": "solo_referencia"},
    {"handle": "@cinestillfilm", "nombre": "CineStill Film", "seguidores": 291799, "prioridad": "solo_referencia"},
    {"handle": "@halno", "nombre": "Halno Creative Traveler", "seguidores": 251062, "prioridad": "solo_referencia"},
    {"handle": "@dailycine", "nombre": "DAILYCINE", "seguidores": 249590, "prioridad": "solo_referencia"},
    {"handle": "@le_cinema_world", "nombre": "Le Cinema", "seguidores": 229394, "prioridad": "solo_referencia"},
    {"handle": "@living_filosofico_cultural", "nombre": "Living Filosófico", "seguidores": 60857, "prioridad": "solo_referencia"},
    {"handle": "@la.inercia", "nombre": "Carla Historia del Arte", "seguidores": 403938, "prioridad": "solo_referencia"},
    {"handle": "@enamorarteangeles", "nombre": "Enamorarte Ángeles", "seguidores": 145575, "prioridad": "solo_referencia"},
    {"handle": "@centro_estudios_fil", "nombre": "Centro de Estudios Filosóficos", "seguidores": 89421, "prioridad": "solo_referencia"},
    {"handle": "@aproximacion_al_arte", "nombre": "Aproximación al Arte", "seguidores": 81052, "prioridad": "solo_referencia"},
    {"handle": "@elponzophoto", "nombre": "Alfonso León Fotografía", "seguidores": 80886, "prioridad": "solo_referencia"},
    {"handle": "@zetafp", "nombre": "Zeta Fernández Archivo Fotográfico", "seguidores": 80554, "prioridad": "solo_referencia"},
    {"handle": "@manuecheverri", "nombre": "Manuela Echeverri Diseño", "seguidores": 202002, "prioridad": "solo_referencia"},
    {"handle": "@pomppestudio", "nombre": "Pomppe Studio Muebles", "seguidores": 124719, "prioridad": "solo_referencia"},
    {"handle": "@zambo.design", "nombre": "Juliana Jurado Diseño", "seguidores": 204543, "prioridad": "solo_referencia"},
    {"handle": "@eterea_eco", "nombre": "Etérea Plantas Diseño", "seguidores": 95502, "prioridad": "solo_referencia"},
    {"handle": "@joeclarkestudio", "nombre": "Joe Clarke", "seguidores": 93100, "prioridad": "solo_referencia"},
    {"handle": "@dicreem", "nombre": "DiCreem Diseño Latino", "seguidores": 211969, "prioridad": "solo_referencia"},
    {"handle": "@invade.design", "nombre": "Invade Design", "seguidores": 23753, "prioridad": "solo_referencia"},
    {"handle": "@angel.mato", "nombre": "Angel Mato Filmmaker", "seguidores": 102536, "prioridad": "solo_referencia"},
    {"handle": "@omar_portela", "nombre": "Omar Portela Fotografía", "seguidores": 21382, "prioridad": "solo_referencia"},
    {"handle": "@andreainesfotografia", "nombre": "Andrea Inés Fotografía Analógica", "seguidores": 9834, "prioridad": "solo_referencia"},
    {"handle": "@cinephileart", "nombre": "MUSE Cine", "seguidores": 97010, "prioridad": "solo_referencia"},
    {"handle": "@redapplecine", "nombre": "Agus López Cine", "seguidores": 96916, "prioridad": "solo_referencia"},
    {"handle": "@cinetonicx", "nombre": "CINEMATIC", "seguidores": 17348, "prioridad": "solo_referencia"},
    {"handle": "@wearecinewood", "nombre": "Cinewood", "seguidores": 73946, "prioridad": "solo_referencia"},
    {"handle": "@cinematicshine", "nombre": "Cinematic Shine", "seguidores": 199801, "prioridad": "solo_referencia"},
    {"handle": "@cinematic_labels", "nombre": "Cinematic Labels", "seguidores": 193545, "prioridad": "solo_referencia"},
    {"handle": "@3amchronicles", "nombre": "3am Chronicles", "seguidores": 91273, "prioridad": "solo_referencia"},
    {"handle": "@cine.fact", "nombre": "Cine Fact", "seguidores": 28983, "prioridad": "solo_referencia"},
    {"handle": "@thelegendsofmusictv", "nombre": "The Legends of Music TV", "seguidores": 151378, "prioridad": "solo_referencia"},
    {"handle": "@musicas_enlazadas", "nombre": "Músicas Enlazadas", "seguidores": 165546, "prioridad": "solo_referencia"},
    {"handle": "@musicrisepr", "nombre": "Music Rise PR", "seguidores": 131411, "prioridad": "solo_referencia"},
    {"handle": "@canserberomusic.1", "nombre": "Canserbero Tributo", "seguidores": 41805, "prioridad": "solo_referencia"},
    {"handle": "@__canal333", "nombre": "CANAL 333 Diseño y Arte", "seguidores": 39137, "prioridad": "solo_referencia"},
    {"handle": "@dondeestamaiz", "nombre": "Tayz Planes en Cali", "seguidores": 30281, "prioridad": "solo_referencia"},
    {"handle": "@makrabeus", "nombre": "MAKRABEUS Director Creativo", "seguidores": 32499, "prioridad": "solo_referencia"},
    {"handle": "@trespimedios", "nombre": "Tres Pi Medios", "seguidores": 21356, "prioridad": "solo_referencia"},
    {"handle": "@paddock_ps", "nombre": "Paddock Performance Shop", "seguidores": 26897, "prioridad": "solo_referencia"},
    {"handle": "@opengymcreativo", "nombre": "OPENGym Comunidad Creativa", "seguidores": 14706, "prioridad": "solo_referencia"},
    {"handle": "@unreadsociety", "nombre": "Sebastian Bookstagram", "seguidores": 8248, "prioridad": "solo_referencia"},
    {"handle": "@mati.creativo", "nombre": "Matías Esteban", "seguidores": 3827, "prioridad": "solo_referencia"},
    {"handle": "@valledeluzcreativo", "nombre": "Valle de Luz", "seguidores": 370, "prioridad": "solo_referencia"},
    {"handle": "@mentecreativa2020", "nombre": "Mentecreativa2020", "seguidores": 2414, "prioridad": "solo_referencia"},
    {"handle": "@creatuvida2020", "nombre": "Creativa", "seguidores": 35, "prioridad": "solo_referencia"},
    {"handle": "@reelsmakerforever", "nombre": "Video Reels Maker", "seguidores": 4108, "prioridad": "solo_referencia"},
    {"handle": "@tms.cinematic", "nombre": "Thomas Cinematic", "seguidores": 1439, "prioridad": "solo_referencia"},
    {"handle": "@janhendrickslm", "nombre": "Creative Art Jan", "seguidores": 1514, "prioridad": "solo_referencia"},
    {"handle": "@sobrenatural.hijos.de.dios", "nombre": "Sobrenatural Grupo de Oración", "seguidores": 483, "prioridad": "solo_referencia"},
    {"handle": "@odontos_grupodental", "nombre": "Odontos Grupo Dental", "seguidores": 1563, "prioridad": "solo_referencia"},
    {"handle": "@pelistreaming.net11", "nombre": "Plataformas de Entretenimiento", "seguidores": 61, "prioridad": "solo_referencia"},
    {"handle": "@acant.col", "nombre": "ACANT Antropología Colombia", "seguidores": 3890, "prioridad": "solo_referencia"},
    {"handle": "@mesla_sociales_uba", "nombre": "Maestría Estudios Sociales UBA", "seguidores": 579, "prioridad": "solo_referencia"},
    {"handle": "@estudioslatinoamericanosupb", "nombre": "Estudios Latinoamericanos UPB", "seguidores": 697, "prioridad": "solo_referencia"},
    {"handle": "@mielsamana", "nombre": "Samaná Mieles", "seguidores": 11613, "prioridad": "solo_referencia"},
    {"handle": "@mihabitacion1", "nombre": "Habitaciones Amobladas", "seguidores": 10463, "prioridad": "solo_referencia"},
    {"handle": "@senor_bolson", "nombre": "Señor Bolsón Cerveza", "seguidores": 1103, "prioridad": "solo_referencia"},
    {"handle": "@choripan_nea", "nombre": "Choripan-nea", "seguidores": 7010, "prioridad": "solo_referencia"},
    {"handle": "@circolate", "nombre": "Cía Circolate", "seguidores": 894, "prioridad": "solo_referencia"},
    {"handle": "@auditumfest", "nombre": "Auditum Plataforma de Escuchas", "seguidores": 2931, "prioridad": "solo_referencia"},
]


# ═══════════════════════════════════════════════════════════════
# FUNCIONES AUXILIARES
# ═══════════════════════════════════════════════════════════════

def get_all_local_profiles(min_priority: str = "baja") -> list[dict]:
    """
    Retorna TODOS los perfiles locales (Valle de Aburrá) para monitoreo.
    Filtra por prioridad mínima: alta > media > baja.
    """
    priority_order = {"alta": 1, "media": 2, "baja": 3, "solo_referencia": 4}
    min_val = priority_order.get(min_priority, 3)

    all_lists = [
        MUSEOS, TEATROS, MUSICA, CINE, FOTOGRAFIA, LITERATURA, EDITORIALES,
        FUNDACIONES, COLECTIVOS, GALERIAS, FESTIVALES, ESPACIOS_CULTURALES,
        INSTITUCIONALES, RADIO_PODCASTS, DANZA, ARTE_DISENO,
    ]

    profiles = []
    seen = set()
    for lst in all_lists:
        for item in lst:
            handle = item.get("handle", "")
            if handle in seen:
                continue
            seen.add(handle)
            p = priority_order.get(item.get("prioridad", "baja"), 3)
            if p <= min_val and item.get("municipio"):
                profiles.append(item)

    return profiles


def get_high_priority_profiles() -> list[dict]:
    """Retorna solo perfiles de prioridad alta (organizan eventos frecuentemente)."""
    return get_all_local_profiles(min_priority="alta")


def get_all_handles_for_scraping() -> list[str]:
    """Retorna todos los handles locales para scraping de agenda cultural."""
    profiles = get_all_local_profiles(min_priority="baja")
    return [p["handle"] for p in profiles]


def get_semilla_as_colectivos() -> list[dict]:
    """Convierte todos los perfiles locales al formato colectivo para registro."""
    profiles = get_all_local_profiles(min_priority="baja")
    colectivos = []
    for p in profiles:
        colectivos.append({
            "nombre": p.get("nombre", p["handle"].lstrip("@")),
            "handle": p["handle"],
            "plataforma": "instagram",
            "categoria": p.get("categoria", "arte_general"),
            "municipio": p.get("municipio", "Medellín"),
            "fuente": "semilla_verificada",
            "seguidores": p.get("seguidores", 0),
            "prioridad": p.get("prioridad", "media"),
        })
    # Also include original SEMILLA
    for s in SEMILLA:
        handle = s.get("handle", "")
        if not any(c["handle"] == handle for c in colectivos):
            colectivos.append(s)
    return colectivos


def get_total_count() -> dict:
    """Retorna estadísticas de la red cultural."""
    all_lists = [
        ("museos", MUSEOS), ("teatros", TEATROS), ("musica", MUSICA),
        ("cine", CINE), ("fotografia", FOTOGRAFIA), ("literatura", LITERATURA),
        ("editoriales", EDITORIALES), ("fundaciones", FUNDACIONES),
        ("colectivos", COLECTIVOS), ("galerias", GALERIAS),
        ("festivales", FESTIVALES), ("espacios_culturales", ESPACIOS_CULTURALES),
        ("institucionales", INSTITUCIONALES), ("radio_podcasts", RADIO_PODCASTS),
        ("danza", DANZA), ("arte_diseno", ARTE_DISENO),
        ("internacionales_ref", INTERNACIONALES_REF),
    ]
    stats = {}
    total = 0
    local = 0
    for name, lst in all_lists:
        stats[name] = len(lst)
        total += len(lst)
        local += sum(1 for x in lst if x.get("municipio"))
    stats["total_perfiles"] = total
    stats["total_locales"] = local
    stats["semilla_original"] = len(SEMILLA)
    return stats
