-- ============================================================
-- Import completo desde MARKDOWN (SBPM + UVAs + Teatros)
-- Requiere migracion: 2026_05_equipamientos_zonas_ml.sql
-- ============================================================

WITH src AS (
  SELECT $md$
# Base de datos de equipamientos culturales de Medellín 2026

**93 equipamientos culturales documentados** en tres grupos: 32 unidades del Sistema de Bibliotecas Públicas, 19 UVAS vigentes (más espacios análogos), y 42 teatros oficiales y alternativos. La información proviene de portales oficiales (bibliotecasmedellin.gov.co, bibliotecapiloto.gov.co, grupo-epm.com, inder.gov.co, medellin.gov.co, sitios institucionales de cada teatro) y fuentes periodísticas verificables. Los campos sin confirmación documental se marcan **"Por verificar"**; no se inventaron datos. Los hallazgos críticos para 2026: el Parque Biblioteca Santo Domingo Savio (ex-España) reabre parcialmente entre febrero y mayo de 2026 con operación de la EDU; el Teatro Lido está cerrado en restauración (reapertura prevista 2027); el Teatro Suramericana figura "fuera de servicio"; el programa UVA mantiene 19 espacios activos repartidos entre Fundación EPM (14) e INDER (5), pero la administración Gutiérrez 2024–2027 los reemplaza conceptualmente con los nuevos "ReCreos Deportivos y Culturales".

---

## GRUPO 1 — Sistema de Bibliotecas Públicas de Medellín (SBPM)

Estructura oficial 2026: **10 Parques Biblioteca + 12 bibliotecas de proximidad + 2 centros de documentación + Casa de la Literatura San Germán + Casa de la Lectura Infantil + BPP central + 4 filiales BPP + estrategia itinerante "Parque al Barrio"**. Conmutador central: (604) 385 5555 / 557 0213. Correo institucional: comunicaciones@bibliotecasmedellin.gov.co. Redes generales: @bibliotecasmed (IG, FB, X).

| # | Nombre oficial | Tipo | Dirección | Barrio | Comuna | Zona | Web | Facebook | Instagram | Teléfono | Correo | Horario | Aforo | Categorías | Observaciones |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 1 | Biblioteca Pública Piloto para América Latina – Sede Central | Biblioteca patrimonial / ente descentralizado | Cra 64 #50-32 | Carlos E. Restrepo | 11 Laureles-Estadio | Centro-Occidental | bibliotecapiloto.gov.co | /BibliotecaPublicaPiloto | @bibliotecapiloto | (604) 460 0590 | direccion@bibliotecapiloto.gov.co | L-V 8:30-19:00; Sáb 9:00-18:00 | Auditorio mayor + salas Antioquia, juvenil, experimental | Literatura, Talleres (Taller de Poesía Jaime Jaramillo Escobar 1985), Cine, Patrimonio, Artes Plásticas, Música, Comunidad, Tecnología | Activa. Patrimonio bibliográfico de Antioquia (>140.000 ref.). Mural Pedro Nel Gómez 1979-80 |
| 2 | Filial Juan Zuleta Ferrer (BPP) | Filial BPP | Cra 49A #80-46 | Campo Valdés | 4 Aranjuez | Nororiental | bibliotecapiloto.gov.co/filial-juan-zuleta-ferrer | /BibliotecaPublicaPiloto | Por verificar | (604) 423 8587 / 211 8232 | filial.juanzuleta@bibliotecapiloto.gov.co | L-V 10-18; Sáb 10-17 | Sala lectura, ludoteca, aula múltiple | Literatura, Infancia, Talleres, Comunidad, Cine, Música | Activa. Fundada julio 1986 |
| 3 | Filial Tren de Papel "Carlos Castro Saavedra" (BPP) | Filial BPP | Cl 113 #70-105 (Coliseo Multipropósito) | Florencia | 5 Castilla | Noroccidental | bibliotecapiloto.gov.co | /BibliotecaPublicaPiloto | Por verificar | (604) 473 7978 / 462 4548 | filial.trendepapel@bibliotecapiloto.gov.co | L-V 10-18; Sáb 10-17 | Sala lectura | Literatura, Infancia, Cine, Talleres, Música | Activa. Originalmente operó en vagones de tren |
| 4 | Filial San Javier La Loma (BPP) | Filial BPP | Cra 124 #53B-40, Vereda La Loma | La Loma | Corregimiento 60 San Cristóbal | Corregimientos | bibliotecapiloto.gov.co | /BibliotecaPublicaPiloto | Por verificar | (604) 438 5761 | filial.laloma@bibliotecapiloto.gov.co | L-V 8-17; Sáb 9-13 | Sala rural, ludoteca | Literatura, Cine, Patrimonio, Comunidad, Talleres | Activa rural |
| 5 | Filial San Antonio de Prado (BPP) | Filial BPP | Cra 79 #40 sur-40, Centro Desarrollo Cultural | San Antonio de Prado centralidad | Corregimiento 80 SAP | Corregimientos | bibliotecapiloto.gov.co | /BibliotecaPublicaPiloto | Por verificar | (604) 286 9631 | filial.sanantoniodeprado@bibliotecapiloto.gov.co | L-V 9-18; Sáb 9-14 | Sala lectura, salón musical | Literatura, Música, Talleres, Comunidad, Patrimonio | Activa desde 1958 |
| 6 | Parque Biblioteca Santo Domingo Savio (ex-España) | Parque Biblioteca | Cra 32 #106A-28 (estación Metrocable Santo Domingo) | Santo Domingo Savio | 1 Popular | Nororiental | bibliotecasmedellin.gov.co/parque-biblioteca-nororiental | /Biblioteca.Nororiental | Por verificar | (604) 528 9495 / 300 881 3945 | coordinacion.santodomingo@bibliotecasmedellin.gov.co | Por verificar (reapertura) | 3 cajas; 14.265 m² públicos; 3.727 m² construidos | Eventos masivos, Literatura, Tecnología, Comunidad, Infancia, Música, Cine | **EN REAPERTURA 2026.** Cerrado desde 2015 por fallas estructurales (diseño Mazzanti). Renombrado dic 2024. Contrato EDU sept 2025 ($3.600 mill). Cajas 1 y 2 entre feb-may 2026; Caja 3 después. Mientras opera "Parque al Barrio" |
| 7 | Parque Biblioteca León de Greiff – La Ladera | Parque Biblioteca | Cl 59A #36-30 | La Ladera (antigua Cárcel Celular) | 8 Villa Hermosa | Centro-Oriental | bibliotecasmedellin.gov.co/blog/parque-biblioteca-leon-de-greiff-la-ladera | /PBLaLadera | @pbladera (PV) | (604) 557 0405 / 385 7538 | coordinacion.ladera@bibliotecasmedellin.gov.co | L-Sáb 9-19; Dom/fest 10-16 | Auditorio, salas, terrazas | Teatro, Música, Danza, Artes Plásticas, Cine, Literatura, Talleres, Tecnología, Infancia, Comunidad, Patrimonio, Eventos masivos | Activa. Inaug. 17-feb-2007. Arq. Mazzanti. Atiende ~357.000 hab |
| 8 | Parque Biblioteca Tomás Carrasquilla – La Quintana | Parque Biblioteca | Cra 80 #82-60 | López de Mesa (Robledo) | 7 Robledo | Noroccidental | bibliotecasmedellin.gov.co/blog/parque-biblioteca-tomas-carrasquilla-la-quintana | /PBLaQuintana | @pblaquintana | (604) 557 0401 / 385 7319 | coordinacion.quintana@bibliotecasmedellin.gov.co | L-Sáb 9-19; Dom/fest 10-16 | Auditorio, sala expo, ludoteca, mirador | Literatura, Cine, Artes Plásticas, Talleres, Infancia, Tecnología, Música, Comunidad, Patrimonio, Eventos masivos | Activa. Inaug. 10-mar-2007. Arq. La Rotta. 12.700 m² lote |
| 9 | Parque Biblioteca Presbítero José Luis Arroyave – San Javier | Parque Biblioteca | Cl 42C #95-50 | Campo Alegre / San Javier | 13 San Javier | Centro-Occidental | bibliotecasmedellin.gov.co/parque-biblioteca-presbitero-jose-luis-arroyave-san-javier | /PBSanJavier | @pbsanjavier | (604) 557 0398 / 385 5555 ext 7313 | coordinador.sanjavier@bibliotecasmedellin.gov.co | L-Sáb 9-20; Dom/fest 11-17 | Salas, Makerspace, CEDEZO, ludoteca | Teatro, Música (Festival del Porro Comuna 13), Danza, Artes Plásticas, Cine, Literatura, Talleres, Tecnología (Makerspace, IA), Infancia, Comunidad, Patrimonio, Eventos masivos | Activa. **Primer parque biblioteca** (31-dic-2006). Acceso Metro San Javier |
| 10 | Parque Biblioteca Belén | Parque Biblioteca | Cra 76 #18A-19 | Belén | 16 Belén | Suroccidental | bibliotecasmedellin.gov.co/parque-biblioteca-belen | /ParqueBibliotecaBelen | @parquebibliotecabelen | (604) 557 0425 / 385 5555 ext 6790 | coordinacion.belen@bibliotecasmedellin.gov.co | L-Sáb 9-20; Dom/fest 10-16 | Sala Japonesa, teatro, salas digitales | Teatro, Música, Danza, Artes Plásticas, Cine, Literatura, Talleres, Tecnología, Infancia, Comunidad, Patrimonio, Eventos (Distrito Otaku) | Activa. Diseño arq. japonés Hiroshi Naito. Operada por Comfenalco |
| 11 | Parque Biblioteca Manuel Mejía Vallejo – Guayabal | Parque Biblioteca | Cra 65 #14-115 | Guayabal | 15 Guayabal | Suroccidental | bibliotecasmedellin.gov.co/parque-biblioteca-manuel-mejia-vallejo-guayabal | /PBGuayabal | @pbguayabal | (604) 557 0390 / 351 0495 | coordinacion.guayabal@bibliotecasmedellin.gov.co | L-Sáb 8-19; Dom/fest 11-17 | Sala General, Mediática, aulas-taller | Teatro, Música (Tango), Danza, Artes, Cine, Literatura, Talleres, Tecnología (3D), Infancia, Comunidad, Patrimonio (arqueológico), Eventos | Activa. Inaug. 23-jul-2012. Único PB en zona industrial |
| 12 | Parque Biblioteca Fernando Botero – San Cristóbal | Parque Biblioteca | Cl 62 #131-80 | San Cristóbal centralidad | Corregimiento 60 San Cristóbal | Corregimientos | bibliotecasmedellin.gov.co/blog/parque-biblioteca-fernando-botero-san-cristobal | /PBSanCristobal | @pbsancristobal | (604) 557 0395 / 385 2964 | coordinacion.sancristobal@bibliotecasmedellin.gov.co | L-Sáb 9-20; Dom/fest 10-16 | Salas, Makerspace, escuela música, auditorio | Teatro, Música, Danza, Artes, Cine, Literatura, Talleres, Tecnología (Makerspace, IA), Infancia, Comunidad, Patrimonio, Eventos | Activa. Inaug. oct-2011. Estatua "El Gato" donada por Botero abr-2012 |
| 13 | Parque Biblioteca José Horacio Betancur – San Antonio de Prado | Parque Biblioteca | Cl 50E Sur #75A-94, Vereda El Vergel | El Vergel | Corregimiento 80 SAP | Corregimientos | bibliotecasmedellin.gov.co/parque-biblioteca-jose-horacio-betancur-san-antonio-de-prado | /PBSanAntoniodePrado | @pbsanantoniodeprado | (604) 557 0407 / 286 2901 | coordinacion.sanantonio@bibliotecasmedellin.gov.co | L-Sáb 9-20; Dom/fest 10-16 | Teatro, salón música, parqueadero | Teatro, Música (Coven Rock Fest), Danza, Artes, Cine, Literatura, Talleres, Recreación (skate), Tecnología, Infancia, Comunidad, Patrimonio campesino, Eventos | Activa. Inaug. 14-dic-2011 |
| 14 | Parque Biblioteca Gabriel García Márquez – Doce de Octubre | Parque Biblioteca | Cra 80 #104-04 | Doce de Octubre | 6 Doce de Octubre | Noroccidental | bibliotecasmedellin.gov.co/blog/parque-biblioteca-gabriel-garcia-marquez-doce-de-octubre | /PBDocedeOctubre | @pbdocedeoctubre | (604) 557 0392 / 557 1229 | coordinacion.docedeoctubre@bibliotecasmedellin.gov.co | L-Sáb 9-20; Dom/fest 10-16 | 5 niveles, Makerspace (3D, láser) | Teatro, Música, Danza, Artes, Cine, Literatura, Talleres, Tecnología, Infancia, Comunidad, Patrimonio, Eventos masivos, Recreación | Activa. Inaug. 19-ago-2013. Diseño tipo periscopio |
| 15 | Parque Biblioteca Nuevo Occidente – Lusitania | Parque Biblioteca | Cra 109A #63B-321, Ciudadela Nuevo Occidente | Las Margaritas / La Aurora | Corregimiento 60 San Cristóbal (limítrofe Comuna 7) | Corregimientos / Noroccidental | bibliotecasmedellin.gov.co/parque-biblioteca-nuevo-occidente-lusitania | /PBNuevoOccidenteLusitania | @pbnuevoocc | (604) 475 4270 | coordinacion.lusitania@bibliotecasmedellin.gov.co | L-Sáb 9:30-18:30; Dom/fest 10-16 | Aulas, sala mediática (3D), terraza | Literatura, Artes, Cine, Talleres, Tecnología (3D, alfabetización digital), Infancia, Comunidad, Patrimonio | Activa. **Décimo y más reciente PB**. Apertura mar 2021. 1.619 m² construidos |
| 16 | Biblioteca Pública Centro Occidental | Biblioteca de proximidad | Cl 39D #112-81 | El Salado, San Javier | 13 San Javier | Centro-Occidental | bibliotecasmedellin.gov.co/biblioteca-publica-centro-occidental-2 | /BibliotecaCenOcc | Por verificar | (604) 511 2133 ext 2700 | centrooccidental@bibliotecasmedellin.gov.co | L-V 9-18; Sáb 10-16 | Salas pequeño-mediano formato | Literatura (Clubes Vía ExLibris, Abraxas), Cine, Talleres, Tecnología, Infancia, Comunidad, Artes (Encuentro Zonal Comuna 13) | Activa. Fundada 21-dic-1995. Convenio Comfenalco |
| 17 | Biblioteca Pública La Floresta | Biblioteca de proximidad | Cra 86 #46-55 | La Floresta | 12 La América | Centro-Occidental | bibliotecasmedellin.gov.co/blog/biblioteca-publica-la-floresta | /bibliotecalafloresta | Por verificar | (604) 557 0388 / 411 9154 | floresta@bibliotecasmedellin.gov.co | L-Sáb 9-19; Dom/fest 10-16 | Sala lectura, huerta | Literatura (Tertulia musical), Música, Cine, Artes (fotografía), Talleres, Tecnología (IA), Infancia, Comunidad, Inclusión visual, Eventos (Hay Festival Forum) | Activa. **Primera biblioteca de proximidad SBPM** (1985). Sede Hay Festival Forum 2025-26 |
| 18 | Biblioteca Pública El Limonar | Biblioteca corregimental | Cl 57 Sur #61-02 | El Limonar 1 | Corregimiento 80 SAP | Corregimientos | bibliotecasmedellin.gov.co/blog/biblioteca-publica-el-limonar | /BibliotecaElLimonar | Por verificar | (604) 557 0411 / 358 1380 | coordinacion.limonar@bibliomed.gov.co | L-V 9-18; Sáb 9-16 | Sala múltiple | Literatura, Cine ("Cinema Limón"), Talleres, Tecnología, Infancia (Medellínglish), Comunidad | Activa. Inaug. 31-oct-1998 |
| 19 | Biblioteca Pública El Poblado | Biblioteca de proximidad | Cl 3B Sur #29B-56, UVA Ilusión Verde | El Poblado | 14 El Poblado | Suroriental | bibliotecasmedellin.gov.co/biblioteca-publica-el-poblado | /bibliotecaelpoblado1 | Por verificar | (604) 557 0419 / 385 5555 | poblado@bibliotecasmedellin.gov.co | L-Sáb 9-18; Dom 10-16 | Sala dentro de UVA con Inder, Buen Comienzo, F. EPM | Literatura, ALFIN, Tecnología, Comunidad, Talleres, Infancia | Activa. Apertura 17-ene-2017 |
| 20 | Biblioteca Pública Ávila – María Agudelo Mejía | Biblioteca de proximidad | Cl 39 #38-21 | El Salvador | 9 Buenos Aires | Centro-Oriental | bibliotecasmedellin.gov.co/biblioteca-publica-maria-agudelo-mejia-avila | /avilabiblioteca | Por verificar | (604) 557 0417 | avila@bibliotecasmedellin.gov.co | L-V 9:30-18; Sáb 9:30-17 | Sala lectura | Literatura (clubes Gabo), Cine, Artes, Talleres, Tecnología, Infancia, Comunidad (Esquina Radio) | Activa. Inaug. 21-nov-2015. Trasladada de Ávila a El Salvador 2019 |
| 21 | Biblioteca Pública Santa Cruz | Biblioteca de proximidad | Cra 48 #98A-63 | Santa Cruz | 2 Santa Cruz | Nororiental | bibliotecasmedellin.gov.co/blog/biblioteca-publica-santa-cruz | /BibliotecaPublicaSantaCruz | Por verificar | (604) 557 0427 | coordinacion.santacruz@bibliotecasmedellin.gov.co | L-V 9-18; Sáb 9-16 | 480 m², sala lectura | Literatura, Tecnología (IA, AutoDraw), Artes, Talleres, Infancia, Comunidad, Patrimonio | Activa. Inaug. agosto 1996 |
| 22 | Biblioteca Público Escolar Granizal | Biblioteca de proximidad | Cra 36B #102C-54 (CREM) | Granizal | 1 Popular | Nororiental | bibliotecasmedellin.gov.co/biblioteca-publico-escolar-granizal | /BibliotecaPublicaGranizal | Por verificar | (604) 557 0429 / 528 9495 | coordinacion.granizal@bibliomed.gov.co | L-V 9-18; Sáb 9-16 | Sala en CREM | Literatura, Talleres "TecnoCuriosos", Tecnología, Infancia, Comunidad | Activa desde 1994. Premio Red de Ideas EPM 2010-11 |
| 23 | Biblioteca Público Escolar Popular No. 2 | Biblioteca de proximidad | Cra 43 #118-26, 1er piso (Casa Cultura APICP) | Popular No. 2 | 1 Popular | Nororiental | bibliotecasmedellin.gov.co/biblioteca-publico-escolar-popular-no-2 | /bibliotecapopulardos | Por verificar | (604) 557 0413 / 521 5210 | coordinacion.popular2@bibliomed.gov.co | L-V 9-18; Sáb 9-16 | Sala lectura | Literatura, Cine, Talleres, Infancia, Comunidad | Activa >37 años. Reabrió sept 2021 tras 18 meses cerrada |
| 24 | Biblioteca Público Corregimental Santa Elena | Biblioteca corregimental | Cl 10 #40 Este-62 (vía Med-Rionegro) | Santa Elena centralidad | Corregimiento 90 Santa Elena | Corregimientos | bibliotecasmedellin.gov.co/biblioteca-publico-corregimental-santa-elena | /BibliotecaSantaElenaMedellin | Por verificar | (604) 557 0409 / 538 0222 | coordinacion.santaelena@bibliomed.gov.co | L-V 9-18; Sáb 9-16 | Sala lectura | Literatura, Talleres (tejido), Tecnología (Lab IA), Infancia, Comunidad, Patrimonio (Ando digitalizando), Artes | Activa desde 1985-86. Premio Nacional Daniel Samper Ortega 2021 |
| 25 | Biblioteca Público Corregimental San Sebastián de Palmitas | Biblioteca corregimental | Cl 20 #0-196, vereda parte central | Parte Central | Corregimiento 50 Palmitas | Corregimientos | bibliotecasmedellin.gov.co/biblioteca-publico-corregimental-san-sebastian-de-palmitas | /BibliotecaPalmitas | Por verificar | (604) 557 0415 / 387 0612 | coordinacion.palmitas@bibliomed.gov.co | L-V 8-17; Sáb 9-16 | Sala rural | Literatura, Cine, Música, Artes (pintura, fotografía), Comunidad (Red Entre Montañas), Talleres, Infancia, Patrimonio | Activa. Inaug. 17-dic-1994. Atiende cinco veredas |
| 26 | Biblioteca Pública Altavista | Biblioteca corregimental | Cl 18 #103-160 (I.E. Débora Arango) | Altavista centralidad | Corregimiento 70 Altavista | Corregimientos | bibliotecasmedellin.gov.co/blog/biblioteca-publica-altavista | /bibliotecaaltavista | Por verificar | (604) 557 0483 / 341 7093 | altavista@bibliotecasmedellin.gov.co | L-V 9-18; Sáb 9-16 | Sala lectura en I.E. | Literatura, Talleres, Cine, Infancia, Comunidad, Patrimonio | Activa. Apertura 19-nov-2015 |
| 27 | Biblioteca Fernando Gómez Martínez – Robledo | Biblioteca de proximidad | Cra 88C #76DD-20 | Robledo Aures | 7 Robledo | Noroccidental | bibliotecasmedellin.gov.co/biblioteca-fernando-gomez-martinez-robledo | /BibliotecaFGM | Por verificar | (604) 557 0217 / 421 6595 | robledo@bibliotecasmedellin.gov.co | L-V 9-18; Sáb 9-16 | Sala lectura, sala informática | Literatura, Cine, Teatro (niños), Artes, Tecnología, Talleres, Infancia, Comunidad, Inclusión discapacidad | Activa. Programa "Otras formas de leer" |
| 28 | Biblioteca Parque al Barrio (estrategia itinerante) | Biblioteca itinerante | Recorre comunas 1-4 (UVAs, CEDEZO, colegios) | Múltiples | 1-4 | Nororiental | bibliotecasmedellin.gov.co/parque-biblioteca-nororiental | /Biblioteca.Nororiental | Por verificar | 300 881 3945 | coordinacion.santodomingo@bibliotecasmedellin.gov.co | Concertados con comunidad | Sin sede física | Literatura (Libro móvil, Cocina y carreta), Cine, Comunidad (Diálogos ciudadanos), Tecnología, Talleres, Infancia, Música, Artes | Activa. Sustituye temporalmente al PB Santo Domingo Savio. Funciona desde 2015. >83.000 personas atendidas |
| 29 | Casa de la Literatura San Germán | Unidad especializada | Cl 63 #75-86 | San Germán | 7 Robledo | Noroccidental | bibliotecasmedellin.gov.co/casa-de-la-literatura-san-german | /casadelaliteraturasangerman | Por verificar | (604) 460 8411 | coordinacion.casadelaliteratura@bibliomed.gov.co | L-Sáb 9-18 | Auditorio, terraza | Literatura (Eventos del Libro, PCLEO), Talleres escritura, Cine, Artes, Teatro, Patrimonio, Comunidad, Eventos | Activa. Sede dirección SBPM |
| 30 | Casa de la Lectura Infantil | Unidad especializada infantil | Cl 51 #45-57 (Casa Barrientos) | Boston | 10 La Candelaria | Centro-Oriental | bibliotecasmedellin.gov.co/casa-de-la-lectura-infantil | /casalecturainfantil | Por verificar | (604) 511 2133 ext 2401 | Por verificar | L-V 9-19; Sáb 9-17; Dom 9-15 | Sala infantil, bebeteca, auditorio (>9.800 ej.) | Literatura, Teatro/escénicas, Talleres, Infancia, Comunidad | Activa. Operada por Comfenalco. Patrimonio arquitectónico |
| 31 | Centro de Documentación Musical El Jordán | Centro especializado | Cl 65 #84-17 | Robledo | 7 Robledo | Noroccidental | bibliotecasmedellin.gov.co/centro-de-documentacion-musical-el-jordan | /ElJordanMedellin | @eljordanmedellin | (604) 479 9947 | jordan@bibliotecasmedellin.gov.co | L-V 10-18; Sáb 10-16 | Sala consulta, audiciones | **MÚSICA** (clásica, jazz, rock, electrónica, folclor, urbano, punk), Patrimonio musical, Cine, Talleres, Comunidad (Trueque musical), Eventos (Medellín Guitar Master) | Activa desde 2017. Audiciones con AlcolirykoZ, Puerto Candelaria, Eternal |
| 32 | Centro de Documentación Buen Comienzo | Centro especializado | Por verificar | Por verificar | Por verificar | Centro | bibliotecasmedellin.gov.co/centro-de-documentacion-buen-comienzo | Por verificar | Por verificar | (604) 345 4675 | buencomienzo@bibliotecasmedellin.gov.co | Por verificar | Sala especializada | Literatura primera infancia, Infancia, Talleres, Investigación pedagógica | Activa. Adscrita a Buen Comienzo |

---

## GRUPO 2 — UVAS de EPM y espacios análogos

Las UVAS (Unidades de Vida Articulada) son el legado del programa Aníbal Gaviria 2012-2015 (EPM/Fundación EPM/EDU/INDER/AMVA). En 2026 hay **19 UVAS vigentes** (17 en Medellín + 1 en Bello + 1 en Itagüí), con dos modelos de operación: **14 bajo Fundación EPM** (modelo "tanque-parque") y **5 bajo INDER Medellín** (Sol de Oriente, Sin Fronteras, Nuevo Occidente, El Paraíso, Huellas de Vida). La Alcaldía Gutiérrez 2024-2027 reemplaza el modelo UVA con los **ReCreos Deportivos (7) y ReCreos Culturales (5)**, en construcción. Línea Fundación EPM: +57 604 448 6960. Correo: contactenos@fundacionepm.org.co. INDER: 369 9000.

| # | Nombre oficial | Tipo / Operador | Dirección | Barrio | Comuna | Zona | Web | Facebook | Instagram | Teléfono | Correo | Horario | Aforo / Área | Categorías | Observaciones |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 1 | UVA de La Esperanza | UVA-EPM (F. EPM) | Cl 96 #34-100 | San Pablo | 1 Popular | Nororiental | grupo-epm.com/site/fundacionepm/quehacemos/programas/uva | /FundacionEPM | @fundacionepm | (604) 522 9977 | contactenos@fundacionepm.org.co | Mar-Dom (PV) | Tanque Moscú; ~3.000 m² | Talleres, Infancia, Comunidad, Tecnología, Música, Literatura, Cine | Primera UVA inaugurada (abr 2014). 10 años en 2024. Vigente |
| 2 | UVA de Los Sueños | UVA-EPM (F. EPM) | Cra 28 #69-04 | Versalles 1 | 3 Manrique | Nororiental | grupo-epm.com/.../uvadelossuenos | /FundacionEPM | @fundacionepm | 292 6711 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Tanque Versalles; auditorio 95 pers. | Talleres, Música, Artes, Infancia, Recreación, Tecnología | Inaug. abr 2014. Vigente |
| 3 | UVA La Libertad | UVA-EPM (F. EPM) | Cl 57 #17B-50 | La Libertad | 8 Villa Hermosa | Centro-Oriental | grupo-epm.com/.../uvalalibertad | /FundacionEPM | @fundacionepm | 221 8380 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | ~3.500 m² | Talleres, Música, Danza, Comunidad, Infancia, Recreación | Vigente desde 2014 |
| 4 | UVA de La Alegría | UVA-EPM (F. EPM) | Cra 41 #79-66 | Santa Inés | 3 Manrique | Nororiental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 263 3062 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Tanque Campo Valdés; 977 m² constr.; auditorio 95 | Talleres, Música, Artes, Tecnología (TIC 19 PCs), Literatura, Infancia, Comunidad | Vigente |
| 5 | UVA Nuevo Amanecer | UVA-EPM (F. EPM) | Cl 107B #23A-138 | La Avanzada | 1 Popular | Nororiental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 292 9777 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Por verificar | Talleres, Música, Infancia, Recreación, Comunidad, Patrimonio | Vigente. Premio internacional arquitectura |
| 6 | UVA de La Armonía | UVA-EPM (F. EPM) | Cra 36 #84-98 (Bello Oriente) | Bello Oriente | 3 Manrique | Nororiental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 527 2617 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Tanque Bello Oriente; mirador | Talleres, Música, Danza, Artes, Cine al aire libre, Infancia, Comunidad, Eventos | Vigente. Atractivo turístico Manrique |
| 7 | UVA de La Imaginación | UVA-EPM (F. EPM) | Cra 40 #61-04 | San Miguel | 8 Villa Hermosa | Centro-Oriental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 292 4654 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Tanque Orfelinato; 2.200 m²; teatro al aire libre; 4 salas acústicas | **MÚSICA** (ensayaderos, grabación), Teatro, Artes, Talleres, Tecnología, Infancia | Vigente. **Premio LafargeHolcim Awards Oro 2015** |
| 8 | UVA Mirador de San Cristóbal | UVA-EPM (F. EPM) | Cra 131 #66-20 | Pedregal Alto | Corregimiento 60 San Cristóbal | Corregimientos | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 427 4384 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Mirador panorámico | Talleres, Música, Infancia, Recreación, Comunidad, Patrimonio | Vigente. Atiende veredas Travesías, Uvito, La Cumbre, El Llano |
| 9 | UVA Los Guayacanes | UVA-EPM (F. EPM) | Cl 65C #94-04 | Cucaracho | 7 Robledo | Noroccidental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 426 0995 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Por verificar | Talleres, Música, Artes, Infancia, Comunidad | Vigente |
| 10 | UVA El Encanto | UVA-EPM (F. EPM) | Cra 76 #104D-01 | Santander | 6 Doce de Octubre | Noroccidental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 419 1502 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | 691 m² constr. + 26.766 m² públicos | Talleres, Música, Recreación, Infancia, Tecnología, Comunidad | Vigente. Inaug. enero 2017. Beneficia ~45.000 hab |
| 11 | UVA de La Cordialidad | UVA-EPM (F. EPM) | Cra 42B #110A-04 | Santo Domingo Savio 1 | 1 Popular | Nororiental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 292 9099 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Por verificar | Talleres, Música, Infancia, Comunidad, Recreación | Vigente. Cerca a estación Metrocable Santo Domingo |
| 12 | UVA Ilusión Verde | UVA-EPM (F. EPM) + Inder + AMVA | Cl 3B Sur #29B-56 | Los Naranjos | 14 El Poblado | Suroriental | grupo-epm.com (link general) | /FundacionEPM | @fundacionepm | 266 4077 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | 31.000 m² (la más grande); cancha sintética, biblioteca, teatro | Talleres, Música, Danza, Teatro, Literatura, Cine, Recreación, Deporte, Infancia, Comunidad, Eventos | Vigente. Inaug. ene 2017 por Federico Gutiérrez. Inversión $24.724 mill |
| 13 | UVA Aguas Claras | UVA-EPM (F. EPM) | Diagonal 50A Av. 20-251 | Navarra | Bello (AMVA) | Norte AMVA | grupo-epm.com/.../uva-aguas-claras | /FundacionEPM | @fundacionepm | 300 698 5313 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Junto a PTAR Aguas Claras | Talleres (educación ambiental), Tecnología, Infancia, Comunidad, Recreación | Vigente. Eje ambiental |
| 14 | UVA San Fernando | UVA-EPM (F. EPM) | Cra 47 #85-256 | San Fernando | Itagüí (AMVA) | Sur AMVA | grupo-epm.com/.../uvasanfernando | /FundacionEPM | @fundacionepm | 354 6547 (PV) | contactenos@fundacionepm.org.co | Mar-Dom | Junto a PTAR San Fernando | Talleres ambientales, Tecnología, Infancia, Comunidad, Recreación | Vigente. Eje ambiental |
| 15 | UVA Sol de Oriente | UVA tipo B (INDER) | Cl 56F #18A-2 | Sol de Oriente / La Libertad | 8 Villa Hermosa | Centro-Oriental | inder.gov.co | /InderMedellin | @indermedellin | 369 9000 | atencionalciudadano@inder.gov.co | L-Sáb 6-22 | ~3.500 m²; cancha sintética, gimnasio aire libre | **Recreación y Deporte**, Talleres, Infancia, Comunidad | Vigente. Mantenimiento Inder $66 mill 2024-25 |
| 16 | UVA Sin Fronteras | UVA tipo B (INDER + Red E-Crea Cultura) | Cra 64 #97A-155 | Tricentenario | 5 Castilla | Noroccidental | inder.gov.co | /uvasinfronteras | Por verificar | 369 9000 ext 660 | atencionalciudadano@inder.gov.co | L-V 9-20; Sáb 9-14 | 4.431 m² públicos + 3.107 m² constr.; máster TV | Teatro, Danza, Artes, Música, Talleres, Tecnología (máster TV), Infancia, Comunidad, Recreación | Vigente. Centro Red E-Crea |
| 17 | UVA Ciudadela Nuevo Occidente | UVA tipo B (INDER + Red E-Crea) | Cra 103C #Cl 64BC-120 | Pajarito / La Aurora | Corregimiento 60 San Cristóbal | Corregimientos | inder.gov.co | /uvanoccidente | Por verificar | 369 9000 | atencionalciudadano@inder.gov.co | L-V 9-20; Sáb 9-14 (PV) | 4 módulos; piscina, salón baile, ludoteka, auditorio cine, polideportivo | Recreación y Deporte (piscina), Teatro, Danza, Música, Cine, Talleres, Infancia, Comunidad, Tecnología | Vigente. Inaug. dic 2015. Conectada con Metrocable J |
| 18 | UVA El Paraíso | UVA tipo B (INDER) | Cl 50E Sur #75A-94 | Cabecera SAP | Corregimiento 80 SAP | Corregimientos | medellin.gov.co/.../uva-el-paraiso-de-san-antonio-de-prado | /InderMedellin | @indermedellin | (604) 444 4144 | atencionalciudadano@inder.gov.co | L-Sáb 6-22 | 3.879 m²; cancha fútbol 7 sintética, skate park, gym | Recreación y Deporte, Talleres, Música (ensayaderos), Infancia (ludoteka), Comunidad | Vigente. Adecuaciones $1.300 mill 2022. **Reconocida ArchDaily entre 10 más importantes del mundo** |
| 19 | UVA Huellas de Vida (San Javier) | UVA tipo B (AMVA + INDER) | Cl 39C #113A-1 | Las Independencias | 13 San Javier | Centro-Occidental | inder.gov.co | /InderMedellin | @indermedellin | (604) 421 4010 (PV) | atencionalciudadano@inder.gov.co | L-Sáb 6-22 | 11.500 m² públicos + 2.100 m² en 3 pisos; cancha acústica (aforo 230); estudio grabación, museo | Recreación y Deporte, Música (estudio, sala acústica), Teatro, Artes (galería), Cine/Audiovisual, Infancia (ludoteca), Patrimonio (memoria Comuna 13), Comunidad, Eventos masivos | Vigente. Inversión $24.745 mill. Entregada nov 2019 tras retrasos por corrupción. Referente reconciliación Comuna 13 |

### UVAS NO ejecutadas / canceladas
Pedregal (cancelada por restricciones técnicas), Altavista (suspendida), La Frontera, Robledo adicional, La Almería/Santa Mónica (solo factibilidad). **No existen** UVAS denominadas "Las Flores", "San Sebastián de Palmitas", "Santa Elena", "Altavista corregimiento", "San Antonio centro", "del Conocimiento" o "La Ilusión" en el catálogo oficial.

### Espacios análogos vigentes 2026

| Nombre | Tipo | Operador | Ubicación | Estado |
|---|---|---|---|---|
| Parque de la Vida | Centro promoción salud | UdeA + Sec. Salud | Cra 51D #62-42, Sevilla, Comuna 4 | **Vigente**. Distinto a UVAs. FB: parquedelavidamedellin |
| ReCreo Deportivo Belén Los Alpes | ReCreo deportivo | EDU + Inder | Belén Los Alpes, C16 | **En obra** desde 2025; entrega Q1 2027. $33.956 mill. 4 pisos. Sala gamer, gym, cancha. Beneficia 18.000-22.000 hab |
| ReCreo Deportivo Altavista | ReCreo deportivo | EDU + Inder | Corr. 70 Altavista | Inició obras mar 2026. $34.400 mill. 5 pisos, 3.600 m² |
| ReCreo Deportivo Brisas | ReCreo deportivo | EDU + Inder | Límite C6 y C7 | Próximo a iniciar 2026 |
| ReCreo Deportivo Santa Cruz | ReCreo deportivo | EDU + Inder | C2 Santa Cruz | Proyectado 2026-27 |
| ReCreo Deportivo Buenos Aires | ReCreo deportivo | EDU + Inder | C9 Buenos Aires | Proyectado 2026-27 |
| ReCreo Deportivo Guayabal | ReCreo deportivo | EDU + Inder | C15 Guayabal | Proyectado 2026-27 |
| ReCreo Deportivo San Cristóbal | ReCreo deportivo | EDU + Inder | Corr. 60 | Proyectado 2026-27 |
| ReCreo Cultural Santa Cruz | ReCreo cultural | EDU + Sec. Cultura | C2 | Proyectado |
| ReCreo Cultural Castilla | ReCreo cultural | EDU + Sec. Cultura | C5 | Proyectado |
| ReCreo Cultural Robledo | ReCreo cultural | EDU + Sec. Cultura | C7 | Proyectado |
| ReCreo Cultural Ciudad del Río | ReCreo cultural | EDU + Sec. Cultura | C14 | Proyectado |
| ReCreo Cultural Guayabal | ReCreo cultural | EDU + Sec. Cultura | C15 | Proyectado |
| Distrito Cinema | Equip. audiovisual | Alcaldía | Por definir | Proyectado |
| Gran Parque Medellín / Mar Medellín | Parque deportivo y recreativo | Alcaldía | Aeroparque JP II + María Luisa Calle + Mariana Pajón | **En obra** desde ago 2025. $195.000-$250.000 mill. 210.000 m². Termina abr 2027 |

---

## GRUPO 3 — Teatros y espacios escénicos de Medellín

### 3A. Teatros oficiales, universitarios y grandes salas

| # | Nombre oficial | Tipo | Dirección | Barrio | Comuna | Zona | Web | Facebook | Instagram | Teléfono | Correo | Horario | Aforo | Categorías | Observaciones |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 1 | Teatro Metropolitano de Medellín "José Gutiérrez Gómez" | Teatro Oficial | Cl 41 #57-30 | La Alpujarra | 10 La Candelaria | Centro | teatrometropolitano.com | /TeatroMetropolitanoMedellin | @teatrometropolitano | (604) 232 2858 | info@teatrometropolitano.com | Taquilla L-V 9-18 | **1.634** (1.262 platea + 372 balcón) | Música (clásica, sinfónica, ópera, jazz, zarzuela), Teatro, Danza, Eventos masivos (Festival Jazz, Temporada Ópera), Infancia | Inaug. 19-feb-1987. Arq. Óscar Mesa. Sede Filarmónica de Medellín |
| 2 | Teatro Pablo Tobón Uribe | Teatro Oficial (Fundación) | Cra 40 #51-24, Av. La Playa | Boston / Distrito San Ignacio | 10 La Candelaria | Centro | teatropablotobon.com | /teatropablotobon | @teatropablotobon | (604) 239 7500 | atencionalpublico@teatropablotobon.com | L-V 9-18 | **883** (luneta 508, balcón 375) | Teatro, Música (rock, metal, jazz, sinfónica, urbano), Danza, Cine, Literatura, Comunidad, Infancia, Formación | Inaug. 2-ago-1967. Arq. Nel Rodríguez. Patrimonio Res. 123/1991 |
| 3 | Teatro Lido | Teatro Oficial (Distrito) | Cra 48 #54-20, Parque Bolívar | Villanueva | 10 La Candelaria | Centro | medellin.gov.co | /TeatroLidoMed | @teatrolido | (604) 251 5334 | secretariadeculturaciudadana@medellin.gov.co | **Cerrado por restauración** | **900** post-restauración | Cine, Música, Teatro, Comunidad, Patrimonio | **EN RESTAURACIÓN.** Inaug. 1945. BIC municipal. Restauración $4.931 mill (mar 2026). Reapertura 2027 |
| 4 | Teatro Ateneo Porfirio Barba Jacob | Centro Cultural / Teatro alternativo | Cl 47 #42-38, Local 9901 Torres Bomboná | Bomboná | 10 La Candelaria | Centro | ateneomedellin.com | /ateneodemedellin | @ateneomedellin | (604) 216 0708 | ateneomed@une.net.co | Funciones jue-sáb 19:30 | **350** | Teatro (adultos, monólogos, humor), Música (rock, metal — Festival Metal Medallo), Poesía, Danza, Formación, Galería | Corp. fundada 1994. Festival Colombiano de Teatro |
| 5 | Teatro Universidad de Medellín "Gabriel Obregón Botero" | Teatro Universitario | Cra 87 #30-65, Campus UdeM | Belén Los Alpes | 16 Belén | Suroccidental | teatro.udemedellin.edu.co | /TeatroUdeM | @teatroudem | (604) 590 4500 ext 30834 | clientesteatro@udemedellin.edu.co | L-V 9-13 / 14-18 | **1.702-1.705** (mayor sala con butacas instaladas en Colombia) | Música (todos géneros, ópera, sinfónica), Teatro, Danza, Comedia, Eventos académicos | Inaug. 26-sep-1985. Arq. Ariel Escobar |
| 6 | Teatro Universitario Camilo Torres Restrepo (UdeA) | Teatro Universitario | Cl 67 #53-108, Bloque 23, Ciudad Universitaria | Sevilla | 4 Aranjuez | Nororiental | udea.edu.co | /TeatroCamiloTorresRestrepo | @teatrocamilotorres | (604) 219 8332 / 219 5178 | teatrocamilotorres@udea.edu.co | L-V 8-19 | **1.200** (4.362 m²) | Cine (35mm/16mm), Teatro, Música, Danza, Eventos académicos, Infancia, Comunidad | Inaug. dic-1969. Arq. Ariel Escobar. ~230 actividades/año, 110.000 espectadores |
| 7 | Paraninfo de la Universidad de Antioquia (Edificio San Ignacio – Aula Máxima) | Auditorio Patrimonial Universitario | Cra 44 #48-72, Plazuela San Ignacio | La Candelaria (San Ignacio) | 10 La Candelaria | Centro | udea.edu.co/paraninfo | /UdeA | @udea | (604) 219 5252 | culturacentro@udea.edu.co | L-V 8:30-20; Sáb 10:30-17 | **350** (Aula Máxima); Aula Múltiple 70; Sala Cine 80 | Literatura, Cine, Música (Paraninfo de Concierto), Conferencias (Martes del Paraninfo), Patrimonio | Sede fundacional UdeA (1803). Monumento Nacional Res. 002/1982 |
| 8 | Teatro al Aire Libre Carlos Vieco Ortiz | Teatro Oficial al aire libre | Cerro Nutibara, Cl 30A | Nutibara | 16 Belén | Suroccidental | medellin.gov.co | /TeatroCarlosVieco | @teatrocarlosvieco | (604) 385 5555 | secretariadeculturaciudadana@medellin.gov.co | Según evento | **~1.500** (capacidad histórica 3.800) | Música (rock, metal, urbano, folclórica andina), Poesía (Festival Internacional de Poesía), Cuentería, Trova, Eventos masivos (Altavoz, Mederock) | Inaug. 1984. Arq. Óscar Mesa. Renovación $9.700 mill (jul 2021). Templo del rock |
| 9 | Centro Cultural Fraternidad – Auditorio Mayor (ITM Fraternidad) | Auditorio Universitario | Cl 54A #30-01, Campus Fraternidad | Sucre / Boston | 8 Villa Hermosa | Centro-Oriental | itm.edu.co | /ITMinstitucional | @itminstitucional | (604) 460 0727 | reservaespacios@itm.edu.co | L-V 8-18 | **1.400** (Mayor); Menor 240 | Música, Teatro, Eventos académicos, Formación, Comunidad | Distrito CTeI |
| 10 | Auditorio ITM La Floresta (Antigua Escuela Popular de Arte) | Auditorio Universitario / Cultural | Cl 47A #85-20 | La Floresta | 12 La América | Centro-Occidental | itm.edu.co | /ITMinstitucional | @itminstitucional | (604) 460 0727 | reservaespacios@itm.edu.co | L-V 8-18 | **215** | Música, Teatro, Formación, Artes | Reabierto 2024 tras remodelación $1.500 mill. Acoge legado EPA |
| 11 | Auditorio Pedro Nel Gómez / Aula Magna ITM Robledo | Auditorio Universitario | Cra 74D #73-2, Ciudadela Pedro Nel Gómez | Pilarica / Robledo | 7 Robledo | Noroccidental | itm.edu.co | /ITMinstitucional | @itminstitucional | (604) 460 0727 | reservaespacios@itm.edu.co | L-V 8-18 | Por verificar (~300-400) | Eventos académicos, Música, Teatro, Radio/TV (estudios) | Sede Facultad Ciencias Exactas |
| 12 | Teatro La Convención – Pascual Bravo | Teatro Universitario | Cl 73 #73A-226, Bloque 23 | Robledo | 7 Robledo | Noroccidental | pascualbravo.edu.co | /InstitucionUniversitariaPascualBravo | @pascualbravo | (604) 448 0520 ext 1062 | teatrolaconvencion@pascualbravo.edu.co | L-V 8-18 | **560** | Eventos académicos, Música, Teatro, Grados, Formación | Acreditada Alta Calidad Res. 012512/2022 |
| 13 | Auditorio Gerardo Molina – U. Nacional sede Medellín | Auditorio Universitario | Cra 65 #59A-110, Bloque 41, Campus El Volador | Robledo | 7 Robledo | Noroccidental | medellin.unal.edu.co | /UNALmed | @unalmedellin | (604) 430 9000 | culturamed@unal.edu.co | L-V 8-18 | Por verificar (~500) | Música ("Mil Años de la Música" últimos miércoles), Cine, Teatro, Eventos académicos | Nombre en honor a Gerardo Molina Ramírez |
| 14 | Teatro Comfama Alfonso Restrepo Moreno (Claustro Comfama) | Teatro Caja Compensación | Cl 48 #43-87, Ed. San Ignacio piso 4 | La Candelaria (San Ignacio) | 10 La Candelaria | Centro | comfama.com/cultura-y-ocio/claustro | /comfama | @comfama | (604) 360 7080 | servicioalcliente@comfama.com | L-V 9-21; Sáb-Dom según función | Sala principal PV; **Patio Teatro ~600** | Teatro (Festival Comfama San Ignacio), Música, Danza, Cine, Formación, Literatura, Exposiciones | Renovación integral 2023-26 (~$74.000 mill). Cuna primer estreno teatral Antioquia (1823) |
| 15 | Centro Cultural Comfama Aranjuez (Antiguo Manicomio Departamental) | Centro Cultural Caja Compensación | Cra 51B #91-95 | Aranjuez | 4 Aranjuez | Nororiental | comfama.com/cultura-y-ocio/centros-culturales/aranjuez | /comfama | @comfama | (604) 360 7080 | servicioalcliente@comfama.com | L-D según programación | **272** auditorio | Cine (cineclub), Teatro, Música, Danza, Biblioteca, Exposiciones, Comunidad, Patrimonio | Edificio patrimonial (manicomio 1892). Adquirido por Comfama 1986 |
| 16 | Teatro Suramericana (Sala SURA) | Teatro Empresarial | Cra 64B #49A-30 | Suramericana | 11 Laureles-Estadio | Centro-Occidental | sura.com/arteycultura | /grupoSURA | @grupo_sura | Por verificar | arteycultura@sura.com.co | **Fuera de servicio** | PV (~400-500) | Música (gratuitos), Cine-arte (histórico) | Inaug. oct-1973. Arq. Óscar Mesa. SURA opera anexo Teatro Sura del Jardín Botánico |
| 17 | Auditorio Himerio Pérez López (Cubo) – Edificio EPM | Auditorio Empresarial | Cl 44 #52-156, Edificio EPM | La Alpujarra | 10 La Candelaria | Centro | grupo-epm.com/site/fundacionepm | /FundacionEPM | @fundacionepm | (604) 380 7400 | fundacionepm@epm.com.co | L-V según evento | **360-400** | Eventos académicos, Música, Conferencias, Cine, Comunidad | Cubo de aluminio 27 m. Operado por F. EPM |
| 18 | Plaza Mayor Medellín – Gran Salón / Salón Multipropósito | Centro de Convenciones | Cl 41 #55-80 | La Alpujarra | 10 La Candelaria | Centro | plazamayor.com.co | /plazamayormed | @plazamayormed | (604) 261 7200 | servicioalcliente@plazamayor.com.co | L-V 8-18 | Gran Salón ~4.000-6.000; Multipropósito 378 | Eventos masivos (ferias, congresos, conciertos), Música, Eventos empresariales, Ferias del Libro, Moda | 2006 fusión Palacio Exposiciones (1976) + CIC. 70.000 m². Sede Colombiamoda, Expoartesano. **No es teatro tradicional** |
| 19 | Auditorio Fundadores – EAFIT | Auditorio Universitario | Cra 49 #7 Sur-50, Bloque 21 | El Poblado / Lalinde | 14 El Poblado | Suroriental | eafit.edu.co/cultura | /UniversidadEAFIT | @universidadeafit | (604) 261 9500 ext 9656 | juisaza@eafit.edu.co | L-V 9-18 | Por verificar (~1.000) | Música (Sinfónica EAFIT, ópera), Teatro (Madriguera), Danza, Literatura, Cine (Cineclub EAFIT), Exposiciones, Eventos académicos | Aula máxima EAFIT |
| 20 | Auditorio Juan Pablo II – UPB | Auditorio Universitario | Circular 1 #70-01, Campus Laureles, Bloque 10 | Laureles | 11 Laureles-Estadio | Centro-Occidental | upb.edu.co | /UPBColombia | @upbcolombia | (604) 354 4544 | comunicaciones@upb.edu.co | L-V 8-18 | **245** Juan Pablo II; Polideportivo Eugenio Restrepo hasta 6.000; Centro FÓRUM 800 | Eventos académicos, Música, Teatro, Grados | Acreditación Multicampus Alta Calidad 8 años (oct-2024) |
| 21 | Teatro El Tesoro | Teatro Comercial Privado | Cra 25A #1A Sur-45, El Tesoro PC, Plaza Teatro nivel 3 | El Poblado / Loma del Tesoro | 14 El Poblado | Suroriental | teatroeltesoro.com | /teatroeltesoro | @teatroeltesoro | (604) 321 1010 ext 142 | info@teatroeltesoro.com | Apertura 1h antes funciones | **889-934** (escenario 165 m²) | Música (jazz, K-pop, sinfónico, flamenco, urbano, sinfónica), Teatro Musical, Stand-up, Danza, Eventos internacionales | Único teatro en CC. Inaug. jun 2021. Programación con Filarmónica, Sinfónica EAFIT, Iberacademy |
| 22 | Auditorio del Museo de Antioquia (Sala del Concejo) | Auditorio de Museo | Cra 52 #52-43, antiguo Palacio Municipal | La Candelaria | 10 La Candelaria | Centro | museodeantioquia.co | /museodeantioquia | @museodeantioquia | (604) 251 3636 | comunicaciones@museodeantioquia.co | Mar-Sáb 10-17:30; Dom 10-16:30 | Por verificar | Artes Plásticas y Visuales (colección Botero), Cine, Literatura, Conversatorios, Música, Eventos educativos | Monumento Nacional. 8.164 obras (Botero, Débora Arango, F.A. Cano) |
| 23 | Teatro – Museo de Arte Moderno de Medellín (MAMM) | Auditorio de Museo | Cra 44 #19A-100, Ciudad del Río | Ciudad del Río / Bo. Colombia | 14 El Poblado | Suroriental | elmamm.org | /elmamm | @el_mamm | (604) 444 2622 | info@elmamm.org | Mar-Sáb 9-18; Dom 10-17 | **256** (puerta 12×6 m a plazoleta) | Cine, Danza, Música, Literatura, Conversatorios, Exposiciones, Eventos educativos | Especializado cine, danza, conciertos |
| 24 | Auditorio Francisco Javier Cisneros – Fundación Ferrocarril de Antioquia | Auditorio Patrimonial | Cl 44 (Av. San Juan), Estación Medellín | La Alpujarra | 10 La Candelaria | Centro | fundacionferrocarrildeantioquia.com | /FundacionFFA | @fundacionffa | (604) 448 1554 | corporativo@ffa.org.co | L-V 8-17 | **160 (ampliable 180)** | Eventos académicos, Empresariales, Culturales, Exposiciones, Patrimonio | BIC Nacional. Antigua Estación Medellín |

### 3B. Teatros alternativos, salas concertadas e independientes

| # | Nombre oficial | Tipo | Dirección | Barrio | Comuna | Zona | Web | Facebook | Instagram | Teléfono | Correo | Horario | Aforo | Categorías | Observaciones |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 25 | Pequeño Teatro de Medellín | Sala Concertada Histórica Mincultura | Cra 42 #50A-12 | La Candelaria (centro) | 10 La Candelaria | Centro-Oriental | pequenoteatro.com | /pequenoteatro | @pequeno_teatrom | (604) 480 7740 | areaacademica@pequenoteatro.com | Mar-Sáb 19:30 | **450** Sala Rodrigo Saldarriaga + **78** Sala Tomás Carrasquilla | Teatro adultos/clásicos/literatura colombiana, Escuela actores, Talleres infancia/juventud/adultos, Biblioteca, Galería | Fundado 1975. Patrimonio Cultural Medellín 1985. Casona republicana. Salas Abiertas 2025 |
| 26 | Casa del Teatro de Medellín | Sala Concertada | Cl 59 #50A-25 | Prado Centro | 10 La Candelaria | Centro-Oriental | casadelteatro.org.co | /casadelteatro | @casadelteatro | (604) 254 0397 / 319 729 7209 | administracion@casadelteatro.org.co | Mié-Sáb 19:30 | **~120** (60 ampliable a 70 según fuente alterna) | Teatro experimental/contemporáneo, Dramaturgia, Talleres especializados (Meisner, dirección), Biblioteca Gilberto Martínez (>11.000 títulos), Formación infantil/juvenil | Fundada 4-ago-1987. "Casa de los estrenos". Sala Concertada Mincultura |
| 27 | Teatro Matacandelas | Sala Concertada Histórica Mincultura | Cl 47 #43-47 | Bomboná | 10 La Candelaria | Centro-Oriental | matacandelas.com | /matacandelas | @matacandelas | (604) 215 1010 / 215 1100 | matacandelas@matacandelas.com | Mié-Sáb 19:30/20:00 | **~140-160** | Teatro repertorio, clásicos, experimental, Cine, Literatura, Música en Cabaret El Cantadero (independiente, black metal, jazz, tango) | Fundado 1979. Patrimonio Cultural Medellín 1991. Anfitrión "Molienda Teatral" |
| 28 | Teatro El Águila Descalza – Teatro Prado | Teatro alternativo / Sala Concertada | Cra 45D #59-01 | Prado | 10 La Candelaria | Centro-Oriental | aguiladescalza.com.co | /aguiladescalza | @aguiladescalza | (604) 254 2008 / 284 4211 | aguila@aguiladescalza.com.co | Jue-Sáb 20:00 | **460** | Humor costumbrista, Teatro adultos, Café, Museo, Galería | Cristina Toro y Carlos Mario Aguirre. Mansión patrimonial 1919. 29 obras catálogo |
| 29 | Solar del Águila | Café-teatro alternativo | Cl 47 #42-57 | La Candelaria | 10 La Candelaria | Centro-Oriental | Por verificar | Por verificar | @solardelaguila | Por verificar | Por verificar | Por verificar | Por verificar | Café-teatro, Lecturas, Conciertos, Charlas | Espacio complementario Águila Descalza |
| 30 | Teatro El Trueque | Teatro alternativo / Sala Concertada | Cra 49 #65-28 | Prado / La Candelaria | 10 La Candelaria | Centro-Oriental | teatroeltrueque.wixsite.com/teatro-el-trueque | /teatroeltruequemedellin | @teatroeltrueque | (604) 217 2605 / 312 775 3762 | Por verificar | L-Sáb 8-17 (oficina); funciones noche | **~80** | Teatro creación contemporánea, Talleres, Narración, Música, Cine, Formación | Fundado 2001 por estudiantes UdeA. Sala desde 2009. Salas Abiertas 2025 |
| 31 | Teatro Hora 25 | Teatro alternativo | Cra 88 #39-31 | Cristóbal | 12 La América | Centro-Occidental | teatrolahora25.com | /TeatroHora25 | @teatrolahora25 | 310 723 7457 / (604) 252 9991 | teatrolahora25@teatrolahora25.com | L-Mié 9-18; Jue-Vie hasta 22 | Por verificar (~80-100) | Teatro de pensamiento, Autores clásicos (Shakespeare, Eurípides, Kafka), Formación actores, Dramaturgia | Fundado 1989 por Farley Velásquez (Premio Nacional Dirección 2007). Continuidad bajo Carola Martínez |
| 32 | Teatro Oficina Central de los Sueños | Sala Concertada | Cra 43 #52-50 | La Candelaria | 10 La Candelaria | Centro-Oriental | teatrooficinacentral.com | /teatrooficina | Por verificar | (604) 239 4179 | Por verificar | Jue-Sáb funciones | Por verificar (~80) | Teatro adultos, Teatro infantil/títeres, Formación actores, Conciertos zona social MalaBar (vie) | Fundado 5-dic-1997 por Jaiver Jurado. Miembro fundador Medellín en Escena |
| 33 | Teatro Manicomio de Muñecos | Sala Concertada Mincultura | Cl 32 EE #82A-26 | La Castellana / Belén | 12 La América (limítrofe C16) | Centro-Occidental | manicomiodemunecos.com | /manicomiodemunecos | @manicomiodemunecos | (604) 413 1131 / 324 594 1211 | Por verificar | Funciones fin de semana | **120** | Teatro de títeres/muñecos, Infancia, Formación "Ando Titiritiando", Titirifestival | Fundado 1975 por Liliana M. Palacio H |
| 34 | Casateatro El Poblado | Centro Cultural / Sala Concertada | Cra 47B #17B Sur-30 | Santa María de los Ángeles | 14 El Poblado | Suroriental | casateatroelpoblado.com | /CasaTeatroElPoblado | @casateatroelpoblado | (604) 321 1100 / 317 680 3421 | comunicaciones@casateatroelpoblado.com | L-Sáb 10-22 | **156** silletería / 220 de pie | Teatro contemporáneo, Danza-teatro, Música, Lecturas, Talleres dramaturgia, Eventos académicos, Café-restaurante, Galería | Fundación desde mar 2011, sala desde 25-abr-2013. >200 funciones/año |
| 35 | Corporación Cultural Nuestra Gente – La Casa Amarilla | Casa Cultural / Sala Concertada / Teatro comunitario | Cl 99 #50C-38 | Santa Cruz – La Rosa | 2 Santa Cruz | Nororiental | nuestragente.com.co | /corporacionculturalnuestragente | @nuestragente | (604) 258 0348 | nuestragente@une.net.co | Programación permanente | **~90-100** sala interior + 200 al aire libre | Teatro comunitario, Danza, Música, Formación niños/jóvenes/adultos mayores, Festivales (Encuentro Nacional Teatro Joven), Comparsa | Fundada 1987. Red Colombiana de Teatro en Comunidad. Premio Germán Saldarriaga del Valle 2003 |
| 36 | Corporación Cultural Barrio Comparsa | Corporación cultural | Cl 104EE #83A-48 | El Progreso N° 2 | 6 Doce de Octubre | Noroccidental | Por verificar | Por verificar | Por verificar | Por verificar | corpicacho@une.net.co; info@picachoconfuturo.org | Por verificar | Por verificar | Comparsa, Teatro de calle, Teatro comunitario, Formación juvenil | Vinculada a Picacho con Futuro |
| 37 | Teatro Popular de Medellín (TPM) | Sala Concertada | Cl 48 #41-13 | La Candelaria | 10 La Candelaria | Centro-Oriental | teatropopulardemedellin.com | /TPMTEATROPOPULAR | @teatrotpm | (604) 557 4964 / 216 6262 / 314 882 4808 | teatrotpm@une.net.co | Mar-Sáb según función | Por verificar (~100; 2 salas) | Dramaturgia nacional, Teatro social, Formación, Tango (homenajes Gardel), Infancia, Comunidad | Fundado mar 1979 (sede actual desde 1991). Patrimonio Cultural Medellín 1991. Orden Don Juan del Corral 2004 |
| 38 | Corporación Cultural Vivapalabra | Casa Cultural / Sala Concertada | Cl 55 #43-63 (oficina); funciones Cl 44 #57-21 | La Candelaria | 10 La Candelaria | Centro-Oriental | vivapalabra.com | /vcuenteros | @corporacionvivapalabra | (604) 239 6104 | Por verificar | Funciones semanales | Por verificar | Cuentería, Narración oral, Formación palabra hablada, Festivales "Medellín Sí Cuenta" y "Entre Cuentos y Flores" | Sala Concertada |
| 39 | Teatro Casa Clown (Colectivo Teatral Infusión) | Teatro alternativo / Sala Concertada | Cra 42 #44-46 | Bomboná I | 10 La Candelaria | Centro-Oriental | colectivoinfusion.com | /teatrocasaclown | @teatro_casa_clown | (604) 211 6570 / 320 562 1344 | Por verificar | Funciones varias | Por verificar (~80) | Clown, Teatro físico/gestual, Escuela payasos, Comedia, Formación | Fundado 2008 |
| 40 | Corporación La Fanfarria | Sala Concertada Histórica Mincultura | Cra 84 #42C-54 | La América | 12 La América | Centro-Occidental | lafanfarria.com | /corporacionlafanfarria | Por verificar | (604) 250 9230 | Por verificar | Funciones fin de semana | Por verificar (~150) | Títeres/marionetas, Teatro infantil/familiar, Festivales internacionales | >50 años. Patrimonio Cultural Medellín 1992. Sala Histórica Mincultura 2013 |
| 41 | Casa Tres Patios (C3P) | Centro Cultural / Arte contemporáneo | Cra 50A #63-31 | Prado | 10 La Candelaria | Centro-Oriental | casatrespatios.org | /casatrespatios | @casatrespatios | (604) 571 7798 | Por verificar | L-V oficina | Por verificar | Artes Plásticas y Visuales, Residencias artísticas, Pedagogía crítica, Coordinador Red Artes Visuales Medellín | Fundación sin ánimo de lucro 2006. Tony Evanko y Santiago Vélez |
| 42 | La Pascasia (Corp. Común y Corriente) | Sala Concertada / Casa Cultural / Música | Cl 47 #43-88 | La Candelaria | 10 La Candelaria | Centro-Oriental | lapascasia.org | /casapascasia | @lapascasia | (604) 580 8660 | pascasia@comunycorriente.org | L-Sáb mañana-noche | Auditorio ~200 | Música en vivo (jazz, electrónica, vallenato narrado, músicas tropicales, techno), Teatro, Literatura, Librería, Galería, Café, Podcast/audiovisual | Activa desde 2016. Sede ampliada 4 pisos 2024 |
| 43 | Corporación Artística La Polilla | Sala Concertada / Centro Cultural | Cl 23 #76-85 | Belén San Bernardo | 16 Belén | Suroccidental | lapolilla.com.co | /lapolillamed | @lapolillamed | 310 405 3324 | Por verificar | Funciones jue-sáb | **95** | Teatro, Títeres, Danza, Comparsa, Magia, Karaoke, Cuentería, Formación niños/adultos, Festival Internacional Mimos "MIMAME" | Más de 30 años |
| 44 | Elemental Teatro – Casa Contenta | Teatro alternativo / Casa Cultural rural | Cra 42 #44-46 (urbana); sede principal Vereda Santa Elena | Santa Elena (rural) / La Candelaria (urbano) | Corregimiento 90 Santa Elena | Corregimientos | Por verificar | Por verificar | @elementalteatro | (604) 217 6375 | Por verificar | Por verificar | Por verificar | Teatro de autor, Teatro poético/social, Pedagogía rural | Salas Abiertas 2025 |
| 45 | Teatro La Sucursal | Sala Concertada local | Cra 42 #52-50 | La Candelaria | 10 La Candelaria | Centro-Oriental | Por verificar | Por verificar | @teatro_la_sucursal | (604) 499 3037 | Por verificar | Por verificar | Por verificar | Teatro adultos, Programación regular | Distrito San Ignacio |
| 46 | Teatriados | Sala Concertada local | Cl 61 #49-51 | Prado | 10 La Candelaria | Centro-Oriental | Por verificar | Por verificar | Por verificar | (604) 254 5241 | Por verificar | Por verificar | Por verificar | Teatro alternativo, Formación | Director: Diego Saldarriaga |
| 47 | Teatro Laureles | Centro Cultural / Café-teatro | Tv 39B Circular 2 #46 | Laureles | 11 Laureles-Estadio | Centro-Occidental | Por verificar | Por verificar | @teatro.laureles | (604) 411 8878 (PV) | Por verificar | Por verificar | **250** | Stand-up comedy, Música, Espectáculos baile, Eventos privados | Espacio reciente. Café-bar y 3 auditorios |
| 48 | Acción Impro | Teatro alternativo | Cra 40 #48-57 | La Candelaria | 10 La Candelaria | Centro-Oriental | accionimpro.com.co | /accionimpro | @accionimpro | (604) 444 5432 / 300 365 4992 | Por verificar | Mié-Sáb 20:00 | Por verificar | Improvisación teatral ("Los Impredecibles", "Tríptico"), Academia Creativa | Salas Abiertas 2025 |
| 49 | Fundación Circo Medellín | Sala Concertada / Carpa-circo | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Circo, Artes escénicas | Salas Abiertas 2025 |
| 50 | Corporación Cultural Canchimalos | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Danza folclórica, Teatro comunitario | Salas Abiertas 2025 |
| 51 | Carantoña | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro/títeres infantil | Salas Abiertas 2025 |
| 52 | Corporación Arlequín y Los Juglares | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro infantil/títeres | Salas Abiertas 2025 |
| 53 | Corporación Cultural Barra del Silencio | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro experimental | Salas Abiertas 2025 |
| 54 | Ziruma | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Música/teatro | Salas Abiertas 2025 |
| 55 | Caretas | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro/máscara | Salas Abiertas 2025 |
| 56 | Imagineros | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro infantil/títeres | Salas Abiertas 2025 |
| 57 | Asociación Amigos por la Música | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Música académica | Salas Abiertas 2025 |
| 58 | Corporación Plataforma Cultural | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro/danza | Salas Abiertas 2025 |
| 59 | Teatro Colonial de Robledo José De Los Santos | Sala Concertada local | Por verificar | Robledo | 7 Robledo | Noroccidental | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro comunitario | Salas Abiertas 2025 |
| 60 | Agité Teatro | Sala Concertada local | Itinerante / usa La Polilla | Por verificar | Por verificar | Por verificar | agiteteatro.com | /agiteteatro | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro contemporáneo | Salas Abiertas 2025 |
| 61 | Casa Estudio Pequeños Artistas | Sala Concertada local | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro/formación infantil | Salas Abiertas 2025 |
| 62 | Corporación La Rueda Flotante | Sala Concertada local (nueva 2025) | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Salas Abiertas 2025 |
| 63 | A Puro Tango | Sala Concertada local (nueva 2025) | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Tango/danza | Salas Abiertas 2025 |
| 64 | Taller de Artes de Medellín | Centro de formación / grupo histórico | Vinculado UdeA (PV) | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Por verificar | Teatro, Formación, Ópera, Música clásica | Fundado 1976 por Mario Yepes. Sin sala fija propia activa actual; circuito universitario |
| 65 | Espantapájaros (Grupo de Teatro) | Grupo vinculado a Nuestra Gente | Villa de Guadalupe | Villa de Guadalupe | 1 Popular | Nororiental | Vía Nuestra Gente | Vía Nuestra Gente | Vía Nuestra Gente | Vía Nuestra Gente | Vía Nuestra Gente | Sin sala propia | Sin sala | Teatro juvenil, Comunidad | Grupo dependiente de Nuestra Gente. Tiene semillero "Espantapajaritos" |

### Espacios CERRADOS / NO existentes en Medellín
- **Exfanfarria Teatro**: cerró el 2-dic-2018 (Cl 50B #39-36, Boston). Patrimonio Cultural Medellín Decreto 478/1992. **NO VIGENTE 2026**.
- **Teatro La Mama**: NO está en Medellín. Es de Bogotá (Cl 63 #9-60). Hubo Café-Teatro La Mama en Medellín en los 70 ya desaparecida.
- **Teatro Tespys**: está en El Carmen de Viboral (Oriente antioqueño), no en Medellín.
- **Casa del Encuentro / Vivero del Sur**: sin registro público como espacios escénicos en Medellín.
- **Corporación Colombiana de Teatro Seccional Medellín**: la CCT tiene sede nacional en Bogotá (Casa del Teatro Nacional, sala Seki Sano); no existe seccional Medellín con sala propia.

---

## Notas finales y advertencias metodológicas

**Cobertura territorial.** El SBPM cubre las 16 comunas y los 5 corregimientos, mientras que las UVAS están concentradas en comunas de ladera (1, 3, 8, 13) y corregimientos San Cristóbal y SAP, con vacío en Aranjuez (4), Buenos Aires (9), La Candelaria (10), Laureles (11), La América (12), Belén (16), Guayabal (15), Santa Cruz (2). Los teatros, en contraste, se concentran fuertemente en Comuna 10 La Candelaria (Distrito San Ignacio): allí están más de 25 de los 65 espacios escénicos catalogados.

**Cambios estructurales 2024-2026.** Tres movimientos institucionales clave: (1) el rebautizo del Parque Biblioteca España como **Santo Domingo Savio** (acuerdo del Concejo dic 2024) y su reapertura por etapas en 2026; (2) el reemplazo conceptual del programa UVA por **ReCreos Deportivos y Culturales** bajo operación EDU+Inder+Sec. Cultura (no Fundación EPM); (3) el cierre temporal del **Teatro Lido** para restauración integral con reapertura prevista 2027. Estos hechos deben actualizarse periódicamente en la base.

**Calidad de datos.** Los campos con mayor cobertura son nombre, dirección, comuna, zona, web institucional y categorías de programación. Los campos con más vacíos son: aforos exactos (no centralizados), Instagram individual (muchas usan cuentas centrales @bibliotecasmed, @fundacionepm, @indermedellin), correos electrónicos directos de las salas alternativas, y datos completos de las 14 corporaciones beneficiarias del programa "Salas Abiertas 2025" cuya documentación pública es escasa. **39 entidades requieren verificación adicional vía contacto directo o redes sociales** para completar todos los campos.

**Recomendación operativa.** Antes de alimentar el modelo de IA, validar que los teléfonos siguen activos (algunos provienen de directorios 2015-2017), confirmar las URL de Facebook/Instagram dado que cambian de slug, y consultar el Plan de Desarrollo "Medellín Te Quiere 2024-2027" para incorporar los nuevos equipamientos ReCreo a medida que entren en operación. La fuente más actualizable y autoritativa es el portal **bibliotecasmedellin.gov.co** para Grupo 1, **grupo-epm.com/site/fundacionepm** y **inder.gov.co** para Grupo 2, y **medellinenescena.com.co** junto con la Secretaría de Cultura Ciudadana para Grupo 3.
$md$::text AS md
)
SELECT importar_equipamientos_2026_desde_markdown(md) AS resumen
FROM src;

-- Fallback: asignar zona_slug con normalizacion mas tolerante
UPDATE equipamientos_culturales_2026 e
SET zona_slug = z.zona_slug
FROM zonas_barrios_map z
WHERE e.zona_slug IS NULL
  AND norm_text(z.municipio) = norm_text(e.municipio)
  AND (
    regexp_replace(norm_text(z.barrio_alias), '[^a-z0-9 ]', '', 'g')
      = regexp_replace(norm_text(e.barrio), '[^a-z0-9 ]', '', 'g')
    OR (
      e.barrio IS NULL
      AND e.comuna IS NOT NULL
      AND z.comuna IS NOT NULL
      AND regexp_replace(norm_text(z.comuna), '[^a-z0-9 ]', '', 'g')
        = regexp_replace(norm_text(e.comuna), '[^a-z0-9 ]', '', 'g')
    )
  );

-- Validaciones sugeridas
SELECT
  grupo,
  count(*) AS total,
  count(*) FILTER (WHERE estado_operativo IN ('vigente', 'reapertura')) AS activos
FROM equipamientos_culturales_2026
GROUP BY grupo
ORDER BY grupo;

SELECT
  count(*) AS total_equipamientos,
  count(*) FILTER (WHERE zona_slug IS NULL) AS sin_zona
FROM equipamientos_culturales_2026;

SELECT *
FROM oferta_cultural_por_zona_2026
ORDER BY equipamientos_activos DESC, equipamientos_total DESC
LIMIT 50;
